### ISSUE TITLE
Extract YAML language service to another repo?

### ISSUE THREAD

**Issue by pengx17** [redhat-developer/yaml-language-server#104]
As far as I know, yaml-language-server was invented to make a YAML plugin for code editors (especially vscode), and it is running as a standalone Node.js application in the extension.

To make it running inside of monaco-editor, the yaml language service has to be imported as a module dependency statically with UMD or ESM. What we are doing currently in [monaco-yaml](https://github.com/kpdecker/monaco-yaml) here is to copy `/src/languageservice/*` into our repo as a native module which then could be statically imported, and finally to be built with tsc/vscode bundle helpers. This is clearly not a clean solution. 
A better solution in my opinion is to extract the yaml language service into a new repo and publish it into `vscode-yaml-language-service`. Then both vscode-yaml-languageserver(this repo) and monaco-yaml could depend on it.

What do you think?

**Comment by JPinkney** [comment]
@gorkem @fbricon WDYT? If i'm understanding this correctly I think the pros are that it helps monaco-yaml but on the flip side it seems like we add another level of indirection for users to report issues and this repo would literally just have the server.ts file and include that new dependency. It would still enable it to be its own standalone node js application but this repo would essentially become a shell.

**Comment by fbricon** [comment]
Can't we just publish the server to npm? That should be enough for adopters to depend on it, I don't think it'd require splitting the git repos. 
But I reckon I know next to nothing when it comes to modern javascript toolchain.

**Comment by fbricon** [comment]
mmm it's already available https://www.npmjs.com/package/yaml-language-server

**Comment by pengx17** [comment]
@fbricon it is, but the released bundle is not in a shape which can be imported into a js application statically as a ts lib.
I guess a solution is to have a separate build script to release the service as a typescript library and publish it to npm. Having a separate repo is indeed not necessary any way this way.

**Comment by pengx17** [comment]
Will make one PR for this later.

**Comment by evidolob** [comment]
With https://github.com/redhat-developer/yaml-language-server/pull/305 this should be solved.
