### ISSUE TITLE
Circle CI v2.1 Config Schema not supported

### ISSUE THREAD

**Issue by rjlopezdev** [redhat-developer/yaml-language-server#120]
Extension doesn't validate `.circleci/config.yml`  for v2.1 schema.

![image](https://user-images.githubusercontent.com/18118062/51706772-bab4d900-201f-11e9-9e9f-e43e34fa2745.png)

**Comment by rjlopezdev** [comment]
@JPinkney [error located](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/circleciconfig.json#L416), `"docker"` shouldn't be required.

**Comment by JPinkney** [comment]
So it looks like an issue was filed [here](https://github.com/SchemaStore/schemastore/issues/627) that has to do with what's happening inside the schema. Since this issue doesn't pertain to this project and is instead an issue with the schema, I'm going to close this issue.
