### ISSUE TITLE
Auto-completion should be triggered with [SPACE]

### ISSUE THREAD

**Issue by redborian** [redhat-developer/yaml-language-server#121]
Consider the following example schema:
```json
"Def1": {
  "properties": {
    "sampleEnum": {
      "enums": ["option1", "option2"]
    }
  }
}
```
Typing `Def1:<SPACE>` should automatically trigger auto-completion items (`"option1"` and `"option2"`)

**Comment by JPinkney** [comment]
Hi, this will be added in the next release!

**Comment by JPinkney** [comment]
Unfortunately, we ran into some issues that occur in autocompletion when we added the trigger characters. I've had to revert it for now and an issue is open: https://github.com/redhat-developer/yaml-language-server/issues/129 for getting that fixed. Sorry about that.

**Comment by ssbarnea** [comment]
Official shortcut is ctrl-space for auto completion in vscode.
