### ISSUE TITLE
IntelliJ LSP interaction

### ISSUE THREAD

**Issue by rvansa** [redhat-developer/yaml-language-server#123]
I'd like to use yaml language server from IntelliJ IDEA through the [LSP plugin](https://github.com/gtache/intellij-lsp) but while the README describes all the settings, it doesn't say where to put these when the server is ran from commandline (`--stdio`).

**Comment by rvansa** [comment]
Btw., I couldn't find which version of JSON schema does the server support; I have some issues with [propertyNames](https://json-schema.org/understanding-json-schema/reference/object.html#property-names), trying to apply [this allOf-anyOf trick](https://json-schema.org/draft-06/json-schema-release-notes.html) but either I misunderstand it or there's a bug.

**Comment by JPinkney** [comment]
Sorry for the delay with the response, but currently we don't support propertyNames (though we'd like to bring support for that soon). We currently only support: https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/jsonSchema.ts. I'm not exactly familiar with the Intellij LSP plugin but unfortunately if it looks like they don't have a way to set their settings into the language server via a didChangeConfigurationRequest then I'm not sure how you can go about adding schemas yet

**Comment by Trajamsmith** [comment]
Hi -- is there any update on this? Is there still no way to set schema associations via clients that don't support `didChangeConfigurationRequest`?

**Comment by JPinkney** [comment]
The only other way is to send a notification to the server from the client. This is how its done in VSCode: https://github.com/redhat-developer/vscode-yaml/blob/a24a8c0595652f731767e8af8f660ea9f0002a72/src/extension.ts#L71. 

I don't know how that works in intellij/if thats even supported

**Comment by Trajamsmith** [comment]
Great, thanks @JPinkney ! I'll look into it. We're trying to implement schema validation in JupyterLab using [`jupyterlab-lsp`](https://github.com/krassowski/jupyterlab-lsp).

**Comment by gorkem** [comment]
Closing. I do not think we have anything else left to do here.
