### ISSUE TITLE
Dynamically poll SchemaStore

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/yaml-language-server#124]
This is the yaml version of https://github.com/Microsoft/vscode/issues/26289 .
The JSon schema store also contains schemas for a bunch of yaml files. Enabling support would improve the edition experience without cost for integrators or users.

**Comment by JPinkney** [comment]
I just realized that the readme will need to be updated because the setting is on shown on the VSCode-YAML repo but not this repo, but we actually support the schema store currently and it can be enabled/disabled via yaml.schemaStore.enable setting.

**Comment by mickaelistria** [comment]
Great! And what's the default value?

**Comment by JPinkney** [comment]
Default is true

**Comment by mickaelistria** [comment]
Ok, thank you!

**Comment by mickaelistria** [comment]
and sorry for the noise ;)

**Comment by JPinkney** [comment]
No worries! It's technically my fault because I forgot to add the setting into the readme in this project!
