### ISSUE TITLE
Support latest JSON Schema

### ISSUE THREAD

**Issue by aaron-meyers** [redhat-developer/yaml-language-server#133]
I believe that this project took a fork of the JSON schema validation from https://github.com/Microsoft/vscode-json-languageservice

However the code in this project is quite out of date and doesn't support the latest JSON schema draft specs (draft-06 and draft-07). I was trying to use draft-06 for a JSON schema that is used to validate YAML files in my product but this would break compatibility with the RedHat YAML extension for VS Code.

The JSON service from VS Code supports the latest JSON Schema specs so I think it is just a matter of integrating that new code into this project.

**Comment by JPinkney** [comment]
> The JSON service from VS Code supports the latest JSON Schema specs so I think it is just a matter of integrating that new code into this project.

Correct! Thats one of the goals in the next few versions is to bring up the JSON schema support. Unfortunately the fork of the json parser that we use from the project was heavily modified so we won't be able to integrate it until I make a list of the differences.

**Comment by fbricon** [comment]
@JPinkney is there a way to maybe extend the parser instead of forking it (by making it extensible upstream)? Or any other way to minimize the pain of having to maintain that fork?

**Comment by JPinkney** [comment]
I think it's possible to make the parser extendable upstream. If I'm not mistaken all we would need to do is add a typescript definition file for the json parser and we should be able to extend just based off of that.

**Comment by fbricon** [comment]
Cool. Feel free to open a ticket upstream and ask @aeschli for guidance on how to proceed

**Comment by aeschli** [comment]
A while ago I added [`newJSONDocument`](https://github.com/Microsoft/vscode-json-languageservice/blob/c9d5ec118313b20a8b7de653034a8efb28c285c0/src/jsonLanguageService.ts#L42) to support custom ASTs.
Just implement a parser that creates such an AST and you can reuse most of the functionality offered by the vscode-json-languageservice
