### ISSUE TITLE
'missing field `kind`' when trying to list document symbols

### ISSUE THREAD

**Issue by tterranigma** [redhat-developer/yaml-language-server#134]
I am using neovim with the LanguageClient-neovim plugin. I have opened a simple script file. There, I call the `LanguageClient_textDocument_documentSymbol()` function that is supposed to list the symbols in the document. When I do that, I get a message:

```
[LC] missing field `kind`
```

This is not a code error, it is captured and displayed properly as a message by the LanguageClient plugin.

I am not sure this is a bug with the language server (on vscode it works ok) but I thought I would ask here first.

**Comment by JPinkney** [comment]
Hmm, I've only tried it out in neovim a few times before but the document symbol function should not be reporting errors, those come from elsewhere. Does it happen everytime you use the document symbol function?

To me it looks like the file is associated with a schema and thats where the error message is coming from but I'm not entirely sure

**Comment by tterranigma** [comment]
I am so sorry, I filed this issue to the wrong project...
