### ISSUE TITLE
Formatter must unregister when being disabled

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/yaml-language-server#136]
A formatter that is registered with VSCode must be unregistered when the formatter is being disabled. Otherwise VSCode still thinks a formatter is available, enabling formatting actions and contributing to the problem of conflicting formatters. See Microsoft/vscode#70314 for more details on the topic and feel free to reach out to us for further questions.

Thanks & HappyCoding

**Comment by NikolasKomonen** [comment]
@JPinkney Are you working on this issue already? I'll work on it if you haven't started yet.

**Comment by JPinkney** [comment]
@NikolasKomonen I haven't started it, you'll just have to make sure its consistent with the changes in https://github.com/redhat-developer/yaml-language-server/pull/126 (which I'll probably fixup tomorrow night)
