### ISSUE TITLE
Realign features of YAML Language Server with JSON Language Server

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#142]
Currently, the YAML language server is quite a bit behind the JSON language server in terms of features and will take quite a bit of work to get everything back up to date. This issue will keep track of everything that needs to be done.

- [x] Extend the JSON parser from vscode-json-languageservice rather then use the current version in yaml-language-server
- [x] Replace yamlParser code that recursively builds the AST with new types
- [x] Replace documentSymbols with vscode-json-languageservice's implementation of document symbols and change it to work with YAML's multiple documents
- [x] Replace yamlHover with vscode-json-languageservice's implementation for json, should work the same since theres nothing specific to YAML in this.
- [x] Replace yamlValidation with vscode-json-languageservice's implementation for json, should work the same since theres nothing specific to YAML in this.
- [x] See if there is a way to extend the jsonSchemaService
- [x] See what other features we can use from vscode-json-languageservice that would be relevant

By doing this we solve:
https://github.com/redhat-developer/vscode-yaml/issues/154
https://github.com/redhat-developer/vscode-yaml/issues/151
https://github.com/redhat-developer/yaml-language-server/issues/133
https://github.com/redhat-developer/yaml-language-server/issues/105

**Comment by marosg42** [comment]
@JPinkney I only wanted to bump this issue. I just started to use yaml extension in vscode and realized jsonschema draft-7 enhancement if-then-else is  not available here. It would be really cool to have this available.
