### ISSUE TITLE
Conditionally applying subschemas not working

### ISSUE THREAD

**Issue by leecheve** [redhat-developer/yaml-language-server#149]
JSON schema draft-07 introduces `if`,`then`,`else` keywords to allow the application of a subschema based on the outcome of another schema. The following schema doesn't conditionally apply the subschema: _If the "foo" property equals "bar", then the "baz" property is required_

**test.schema.json**
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "foo": { "type": "string" },
    "baz": { "type": "string" }
  },
  "if": {
    "properties": {
      "foo": { "const": "bar" }
    }
  },
  "then": { "required": ["baz"] },
}
```
**test.yml**
```
foo: bar
```

**Comment by JPinkney** [comment]
We have not released since https://github.com/redhat-developer/yaml-language-server/pull/147 has been merged so the support is still only up to JSON Schema 4. It will be JSON Schema 7 after our next release.

**Comment by JPinkney** [comment]
This should be now working as of 0.7.0.
