### ISSUE TITLE
Functionality without specifying yaml.schemas

### ISSUE THREAD

**Issue by felixfbecker** [redhat-developer/yaml-language-server#15]
I was wondering how good the support is when not specifying `yaml.schemas`? 
Does it automatically query schemas from http://schemastore.org/json/?
Does it support `$schema`?

**Comment by JPinkney** [comment]
It doesn't do any automatic querying to http://schemastore.org/json/ nor does it support $schema afaik but if there is a use case there we might be able to add it. Currently when you don't insert a schema via yaml.schemas the only features are document outlining and regular yaml validation

**Comment by felixfbecker** [comment]
I think it would be awesome to use that. Many applications like ESLint support both JSON and YAML for their config file and that would allow to use the JSON schema that is available in schemastore automatically for .eslintrc.yml files just like VS Code does for .eslintrc.json files.

**Comment by JPinkney** [comment]
I think we already have the basis for that in https://github.com/redhat-developer/vscode-yaml/blob/9fdaa7f62f336def2d425f33ff6599db09c80f28/src/extension.ts#L66 If i'm understanding correctly but we haven't set up any files with it yet. If thats what you're looking for I can definitely add that to the to-do list

**Comment by felixfbecker** [comment]
Not sure what you mean with "haven't set up any files with it yet".

JSON schema store has an API that returns URLs of schemas and glob patterns they should apply to: http://schemastore.org/api/json/catalog.json

**Comment by felixfbecker** [comment]
I just contributed a .travis.yml schema to JSON schema store: https://github.com/SchemaStore/schemastore/pull/368

I think that's the first YAML-only schema so far, so their maintainers definitely seem to be open to use it for YAML

**Comment by JPinkney** [comment]
This is what I was thinking of when I said I haven't set any files up yet: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation. We have a similar property called yamlValidation (https://github.com/redhat-developer/vscode-yaml/blob/master/package.json#L35) that behaves the same way and allows us to setup schemas for specific files

**Comment by felixfbecker** [comment]
it would be best if this extension just queried the schema store API to find a schema to use

**Comment by JPinkney** [comment]
Great news! This should be in our next release!

**Comment by JPinkney** [comment]
I just have a quick question about the travis schema and appveyor schema, I was wondering if you wrote those yourself or if they were generated? We found one small thing with appveyor and then it looks like a few fields are missing in the travis one noted here https://github.com/redhat-developer/vscode-yaml/pull/47

**Comment by felixfbecker** [comment]
Yeah, I just wrote it myself from digging through the documentation. It's definitely not perfect, I noticed things that can be improved myself. `docker` is missing in `services`, array for `os` not possible, not all deploy providers there, ... I think it's like 90% there. Anyone can do a PR to get the last 10% :)

**Comment by JPinkney** [comment]
I'm definitely going to see if theres anything that I can personally add to it to make it better!

**Comment by JPinkney** [comment]
Added in 0.0.7!
