### ISSUE TITLE
command line yaml formatting tool

### ISSUE THREAD

**Issue by nickguo** [redhat-developer/yaml-language-server#171]
Hello,

Is it possible to use yaml-language-server as a command line formatting tool? I see the --stdio option when launching, but I wasn't able to find documentation on how to interact with the language server in that mode.

Could you please include an example on how to use the tool in stdio mode? It's non-obvious to me.

Thanks

**Comment by JPinkney** [comment]
Were you planning on just using this for formatting? If so, then just use the yaml formatter from https://prettier.io/ directly (thats what we use inside of this)

**Comment by nickguo** [comment]
ahh great! yes that's perfect.

Thanks so much :)
