### ISSUE TITLE
Some Yaml files erroneously report Kubernetes diagnostics

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/yaml-language-server#173]
See https://github.com/eclipse/wildwebdeveloper/issues/216 about using the Yaml-ls for Dart specfiles.
A dummy file like
```yaml
name: a
description: b
```
gets parsed as a Kubernetes file and shows some irrelevant errors on the file.
FWIW, the Dart spec file does actually use a name and a description and some other stuff, and isn't a Kubernetes file. No diagnostic should be shown on that file.

**Comment by fbricon** [comment]
Curiously there's no issue in vscode

**Comment by JPinkney** [comment]
I don't think this is an issue with the language server itself. It looks like the eclipse extension is registering kubernetes to attach to all yaml files by default: https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLPreferenceInitializer.java#L30

**Comment by mickaelistria** [comment]
Closing as it's a downstream issue then.
Thanks for your help.
