### ISSUE TITLE
Mergekeys not allowed when JSON schema's are used

### ISSUE THREAD

**Issue by keesschollaart81** [redhat-developer/yaml-language-server#180]
When validating a YAML file with a JSON schema like this:

```JSON
{
    "type": "object",
    "properties": {
        "prop1": {
            "type": "string"
        },
        "prop2": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "required": [
        "prop1"
    ],
    "$schema": "http://json-schema.org/draft-07/schema#"
}
```

It is not possible to use merge keys, it says that '<<' is not a valid property:

![image](https://user-images.githubusercontent.com/6755359/64485682-9363f280-d223-11e9-837f-7e1e718e5c37.png)

Would it be possible to ignore '<<' properties when validating schema's?

**Comment by JohannLai** [comment]
I had the same problem.  😭 
![image](https://user-images.githubusercontent.com/10769405/64498868-18fda600-d2e9-11e9-96bf-56c0ebbc0441.png)

**Comment by nfriend** [comment]
Related: https://github.com/redhat-developer/vscode-yaml/issues/233

**Comment by mapleeit** [comment]
Hi, @JPinkney I noticed that the 0.6.0 already been released. It seems that this version didn't fix this bug.

**Comment by ssbarnea** [comment]
That is a critical bug as use of anchors is almost a guarantee today. It should not be a big deal to fix it because it involves pre-processing the file. The only downside is that reported errors from the schema may not have a line number to reffer to.

**Comment by JPinkney** [comment]
I think I have a fix for this that should make it into the next release, when I was switching everything from using a JSON 4 parser to a JSON 7 parser I missed a part of code that processes merge keys correctly

**Comment by ssbarnea** [comment]
Please do not close bugs without having at least a pre-release. Are there any instructions on how to test master? I may be able to give faster feedback on incoming changes.

**Comment by JPinkney** [comment]
Github auto closed it when that PR was merged. I can reopen it until a version is released.

I'll have to release a new version of vscode-yaml and yaml-language-server before everyone can benefit but if you want to try out the changes before release you can follow: https://github.com/redhat-developer/vscode-yaml#developing-the-client-and-server-together. Depending on how much time I have I might be able to create a pre-release of vscode-yaml in the next few days

**Comment by JPinkney** [comment]
The new version has been released so I'm closing.
