### ISSUE TITLE
uri-reference format validated incorrectly

### ISSUE THREAD

**Issue by jedrichards** [redhat-developer/yaml-language-server#181]
It looks to me like the `uri-reference` format is being incorrectly validated [here](719406ed24f14c861facac393909fbd5cfef/src/languageservice/parser/jsonParser07.ts#L659-L681).

The validation logic seems to assume that any value that doesn't have a parsable uri scheme is invalid, but according to the JSON Schema `uri-reference` can either be a URI or a relative reference.

> A string instance is valid against this attribute if it is a valid URI Reference (either a URI or a relative-reference), according to [RFC3986].
> https://json-schema.org/draft-07/json-schema-validation.html#rfc.section.7.3.5

This is causing issues downstream, for example the JSON Schema [meta schema](https://json-schema.org/draft-07/schema) defines `$ref` values as having the `uri-reference` format, which is causing valid internal and relative `$ref` values to be marked incorrectly as invalid.

```
$ref: some/relative/path/foo.schema.yaml // Invalid
```

```
$ref: #/some/internal/Thing // Invalid
```

```
$ref: file:///some/absolute/path/foo.schema.yaml // Valid
```

Associated issues:

- https://github.com/redhat-developer/vscode-yaml/issues/218
- https://github.com/microsoft/vscode/issues/80029

**Comment by gorkem** [comment]
I have added a few test cases to validation tests which seem to pass happily. Can we close this one ?

**Comment by gorkem** [comment]
Closing, as it can not be reproduced.
