### ISSUE TITLE
YAML Schema files not correctly parsed

### ISSUE THREAD

**Issue by hreeder** [redhat-developer/yaml-language-server#186]
We store our JSON Schemas as YAML files.
I have configured my workspace's `settings.json` as follows
```
{
    "yaml.schemas": {
        "./schema.d/myschema.yaml": "/myfile.yaml"
    }
}
```
However, when I load `myfile.yaml` I get the following error: `Unable to parse content from '/path/to/schema.d/myschema.yaml'`

I would assume the issue lies in https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/jsonSchemaService.ts#L394-L413

Would a pull request to add support for YAML representations of schemas be considered? If so I am happy to attempt to add this.

**Comment by JPinkney** [comment]
I think its been asked before somewhere on https://github.com/redhat-developer/vscode-yaml so it seems like theres enough want to at least consider it

**Comment by hreeder** [comment]
Ah yes, I've just found redhat-developer/vscode-yaml#182

In which case, I've started a bit of an implementation on this yesterday evening and I'll get some bits written up and put into a PR hopefully in the next few days.

**Comment by JPinkney** [comment]
Closing as this task is already done as part of this PR: https://github.com/redhat-developer/yaml-language-server/pull/318
