### ISSUE TITLE
Diagnostics shouldn't span the entire document

### ISSUE THREAD

**Issue by gatesn** [redhat-developer/yaml-language-server#19]
With large files ~10k lines, Monaco/VSCode performance degrades when a diagnostic spans a large number of those lines.

Syntax errors can cause the YAML Language Server to report a diagnostic from the location of the error all the way to EOF. Is it possible to force these errors to be restricted to a single line? Or even character when they cause unrecoverable parser errors?

**Comment by JPinkney** [comment]
I'm going to look into this and see what we can do

**Comment by JiahuiJiang** [comment]
Can we cut a release with the fix? :D thank you!
