### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by mikias** [redhat-developer/yaml-language-server#199]
[Error - 4:31:30 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: workspaceFolders is not iterable.

**Comment by JPinkney** [comment]
Can you give some more info please. What editor are you using? what system? did you set any of the configuration settings etc

**Comment by mikias** [comment]
Editor: VSCode v1.40.0
OS:  MacOS Mojave 10.14.6
Relevant configs: settings.json ...
...

    "yaml.schemas": {
        "Kubernetes": "*.yaml",
        "yaml.format.enable": true,
        "yaml.validate": true,
        "yaml.completion": true
    },
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "[yaml]": {
        "editor.defaultFormatter": "redhat.vscode-yaml"
    }

**Comment by JPinkney** [comment]
This should be fixed in 0.6.1, please try it out and let me know. If it doesn't let me know exact steps I can use to reproduce the issue

**Comment by mikias** [comment]
Looks good. Issue closed 👍
