### ISSUE TITLE
Support $schema reference to JSON schema

### ISSUE THREAD

**Issue by aaron-meyers** [redhat-developer/yaml-language-server#204]
Currently JSON schema for a YAML file must be specified externally, either via settings or from the public schema store.

I'd like to be able to specify the schema to use in the YAML document itself. This is possible with JSON documents by specifying a $schema property, e.g.
```
{
  "$schema": "http://some.org/schema",
  "prop1": "value1"
  ...
}
```

It seems reasonable to me that the same convention could be supported for YAML documents (as this is defined as part of the JSON schema spec itself):

```
$schema: http://some.org/schema
prop1: value1
...
```

**Comment by pappasam** [comment]
This feature would be incredible.

**Comment by apupier** [comment]
I don't think that we can use the notation

```
$schema: http://some.org/schema
prop1: value1
```

because it means that the $schema should be part of the schema definition. It seems quite intrusive.

What about using a comment/[modeline](https://vim.fandom.com/wiki/Modeline_magic)? such as:

```
# json-schema: http://some.org/schema
prop1: value1
```

or

```
# yaml-language-server: json-schema=http://some.org/schema
prop1: value1
```

**Comment by ssbarnea** [comment]
Lets open a sister ticket on YAML meta repository itself, maybe YAML spec authors can help us make a good/future proof decision?

**Comment by apupier** [comment]
> YAML meta repository itself

Can you precise which repository it is please?

**Comment by ssbarnea** [comment]
I think there is an existing ticket at https://github.com/yaml/yaml-spec/issues/33 -- better to comment on it. Also a good channel to engage with spec people is `#yaml-dev` on freenode. Maybe there is some hope...

**Comment by apupier** [comment]
I tried to put a not yet defined directive and unfortunately, they are not ignored. It is reporting a validation error. I think that we can go with a comment `# something` as a first iteration, waiting that Yaml spec introduce the specific Yaml schema directive.
When the yaml schema directive will be available, it will be relatively simple to support it also.

**Comment by apupier** [comment]
implemented using `# yaml-language-server: $schema=http://some.org/schema` format
