### ISSUE TITLE
Server-side snippet support 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/yaml-language-server#205]
It should be possible to pass a list of snippets to the language server that will be offered as code completion options when it is appropriate according to the active schema.

**Comment by JPinkney** [comment]
Linking the draft PR: https://github.com/redhat-developer/yaml-language-server/pull/209

**Comment by gorkem** [comment]
We can implement this support by supporting [defaultSnippets](https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas) vscode extension to json schemas. 

From a quick look #150 is a pre-requisite for porting `defaultSnippets`.

**Comment by JPinkney** [comment]
This is now available as of the 0.7.0 series releases.
