### ISSUE TITLE
Context dependent code completion

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/yaml-language-server#206]
It should be possible to pass code completion options that are dependent on the context. 3rd party extensions should be able to pass the possible values for a field by checking the current context. For instance a kubernetes extension should be able to set the possible values for a field by checking the currently connected cluster. 

One way to implement this is to modify the in-memory Schema that is currently active. I think this can be enough for most cases but the rare quick changing environments.

**Comment by angelozerr** [comment]
@gorkem , did you mean a `completionParticipant` feature? If it that I think it's the same issue than https://github.com/redhat-developer/yaml-language-server/issues/190 and  I'm very glad that you need that and I think YAML Language Server should do that for other features like hover, rename, diagnostics etc (like LSP4XML provides that).

It's out of scope but *Participant will give the capability to communicate with other language server (ex: YAML language server will able to call Spring Tools LS, Quarkus LS in completion and it's the reason why I create the issue [Handle communication between 2 language servers -> language client registry](https://github.com/microsoft/vscode-languageserver-node/issues/526) ( I would like so to convince guys like @tsmaeder with this idea :))

If you are interested with this topic, please see the investigation with LSP4XML with @martinlippert  in the issue https://github.com/angelozerr/lsp4xml/issues/596

**Comment by gorkem** [comment]
@angelozerr A `completionParticipant` is one way but I think for the YAML LSP modifying the effective schema via APIs may prove to be a more efficient solution. Schema controls completion, hover, validation etc. so it is single API to solve all those requirements.

**Comment by JPinkney** [comment]
This is now available as of the 0.7.0 series releases.
