### ISSUE TITLE
Odd behavior with parsing schema for Azure Pipelines

### ISSUE THREAD

**Issue by amasover** [redhat-developer/yaml-language-server#229]
Hello, I'm seeing some odd behavior with this yaml file:

```
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      verbosityPack: minimal
```

In my editor (emacs), this gives me a red underline on `DotNetCoreCLI@2`, with the error:

> String does not match the pattern of "^PowerShell@2$"

I have that yaml file set to use the following schema:

https://github.com/microsoft/azure-pipelines-vscode/raw/master/service-schema.json

In that schema, I've noticed that the `verbosityPack` key in the inputs for the DotNetCoreCLI@2 task is defined like:

```
"verbosityPack": {
	"description": "Verbosity",
	"ignoreCase": "all",
	"enum": [
		"-",
		"Quiet",
		"Minimal",
		"Normal",
		"Detailed",
		"Diagnostic"
	]
},
```

Changing the value of `verbosityPack` from `"minimal"` to `"Minimal"` indeed fixes the red underline in my editor (although it seems, despite what the schema suggests, Azure Pipelines itself will actually accept either).

But I still think there might be something odd going on parsing the schema here (and it leads to confusion with code assist). My best guess is perhaps it's defaulting to matching `^PowerShell@2$` because in the schema, that's the first value in the list of valid tasks.

**Comment by amasover** [comment]
Note: I see the same behavior (red underline with error about not matching `"^PowerShell@2$"`) if, in that same `DotNetCoreCLI@2` task, I choose to use one of the listed aliases for input keys.

For example, I can't use `packagesDirectory` instead of `restoreDirectory` for this input:

```
"restoreDirectory": {
	"type": "string",
	"description": "Destination directory",
	"ignoreCase": "key",
	"aliases": [
		"packagesDirectory"
	]
},
```

**Comment by JPinkney** [comment]
> My best guess is perhaps it's defaulting to matching ^PowerShell@2$ because in the schema, that's the first value in the list of valid tasks.

I believe its matching that part of the schema because it thinks all of the alternative schemas are "just as good" (meaning the same amount of errors will be produced if it uses them, etc). So it chooses to match the first

> Changing the value of verbosityPack from "minimal" to "Minimal" indeed fixes the red underline in my editor (although it seems, despite what the schema suggests, Azure Pipelines itself will actually accept either).

Yeah it looks like the schema will need to be adjusted if both are accepted. The parser has no intelligence, it either matches it perfectly and decides to use that schema or it doesn't match perfectly and chooses to match the best possible option

> I choose to use one of the listed aliases for input keys.

I'm not sure _exacttlyyyy_ what you mean but aliases isn't a [supported part of the json schema](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/jsonSchema.ts) I don't think its in the json schema spec either

**Comment by amasover** [comment]
> The parser has no intelligence, it either matches it perfectly and decides to use that schema or it doesn't match perfectly and chooses to match the best possible option

Forgive my lack of experience here. I think you're saying basically that whatever the value of the `task` key here has no more importance to the parser than any other key, which is why it chooses to match the next best option. This seems a little confusing to me from a user PoV, but if there's no better way to write the parser then I should probably close this issue :)

The behavior is consistent at least. If I add an `asdf` key to inputs, then I also see the message about not matching the PowerShell command.

> Yeah it looks like the schema will need to be adjusted if both are accepted.

I agree with that.

> I'm not sure exacttlyyyy what you mean

I don't know if it's super relevant to the discussion, but basically Azure Pipelines treats these the same:

```
- task: DotNetCoreCLI@2
  inputs:
    packagesDirectory: "./"

- task: DotNetCoreCLI@2
  inputs:
    restoreDirectory: "./"
```

Looks like in the schema the way they do that is using a nonstandard `alias` field. And yeah, since aliases aren't supported in the json schema ([there's some discussion on adding them](https://github.com/json-schema-org/json-schema-vocabularies/issues/5), but at this point seems like it's not supported), it causes oddness in parsing.

In any case, thank you very much for your help.

**Comment by amasover** [comment]
Hmm, it looks like Microsoft has actually forked this project and [added support for aliases](https://github.com/microsoft/azure-pipelines-language-server/pull/33) (among other things).
