### ISSUE TITLE
Duplicate key error is shown in the wrong line

### ISSUE THREAD

**Issue by josa42** [redhat-developer/yaml-language-server#237]
<img width="436" alt="Screen Shot 2020-02-13 at 23 25 55" src="https://user-images.githubusercontent.com/423234/74484093-3d713600-4eb8-11ea-8012-50fd833a6279.png">

- `vscode-yaml`: `0.72`

**Comment by JPinkney** [comment]
Should be fixed in the latest release

**Comment by josa42** [comment]
🎉 Very cool!
