### ISSUE TITLE
duplicate "yaml.format.enable" entry

### ISSUE THREAD

**Issue by joaocc** [redhat-developer/yaml-language-server#24]
After installing the redhat.vscode-yaml, my global default settings file has duplicate entries for``` yaml.format.enable ```.

![screenshot at nov 29 10-33-11](https://user-images.githubusercontent.com/2837860/33370860-bb62a966-d4f0-11e7-8a9c-a93fa8ca0688.png)

**Comment by JPinkney** [comment]
It looks like you have https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml installed as well as this extension. If you remove the other extension it should go away!

**Comment by JPinkney** [comment]
We were in contact with the adamvoss and he originally was going to remove his extension and redirect people from his extension to ours once we supported all his features (thats why those two are identical). In the end he left his extension up, thats why the formatters are identical

**Comment by gorkem** [comment]
closing
