### ISSUE TITLE
Is this a misunderstanding about character position definition?

### ISSUE THREAD

**Issue by jfcherng** [redhat-developer/yaml-language-server#243]
Sorry that I can't find a proper word in the title to phrase it.

I saw this LSP is sending the following payload in https://github.com/sublimelsp/LSP/pull/904.

<details>

```json
:: <-- yaml-lsp textDocument/publishDiagnostics:

{
  "diagnostics": [
    {
      "message": "can not read a block mapping entry; a multiline key may not be an implicit key",
      "range": {
        "end": {
          "character": 114,
          "line": 3
        },
        "start": {
          "character": 114,
          "line": 3
        }
      },
      "severity": 1
    }
  ],
  "uri": "file:///C:/Users/Clover/Desktop/test.yaml"
}
```

</details>

The `character` in the payload seems to be counted from the begin of the file (rather than from the line) at the first glance. Check the [source code](https://github.com/redhat-developer/yaml-language-server/blob/07ca6cadfd3220ad40020207686236b2a857407a/src/languageservice/parser/yamlParser07.ts#L163) makes me feel like that as well. While the [LSP specifications](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#position) says the `character` is counted from the line (basically means `column` I guess).

```ts
interface Position {
	/**
	 * Line position in a document (zero-based).
	 */
	line: number;

	/**
	 * Character offset on a line in a document (zero-based). Assuming that the line is
	 * represented as a string, the `character` value represents the gap between the
	 * `character` and `character + 1`.
	 *
	 * If the character value is greater than the line length it defaults back to the
	 * line length.
	 */
	character: number;
}
```

**Comment by JPinkney** [comment]
It is indeed using the wrong character, it looks like it should only be `e.mark.column`

**Comment by JPinkney** [comment]
Can you try this again using yaml language server 0.9.0 we've updated the way the errors are created

**Comment by jfcherng** [comment]
Yes, I think the response no longer exceed the line length now. Thanks!
