### ISSUE TITLE
Auto-Edit to turn indent tabs into indent spaces

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/yaml-language-server#244]
See https://github.com/eclipse/wildwebdeveloper/issues/372 and https://yaml.org/spec/1.2/spec.html#id2777534 . YAML spec enforces indentation with spaces.
So the language server should provide an -opt-out (since it's spec'd, it should be default- auto conversion on indent tabs into indent spaces.

**Comment by mickaelistria** [comment]
Any chance this can be addressed soon? This is one of the main issue users of Eclipse IDE are facing with Yaml and I'd rather avoid implementing the language-specific feature in the client if this can be addressed by the LS according to the language specification.

**Comment by JPinkney** [comment]
The only way I can think of doing it is by providing enhancements to `OnTypeFormatting` once https://github.com/redhat-developer/yaml-language-server/pull/389 is merged

**Comment by evidolob** [comment]
I think we can provide [CodeAction](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) to convert tab indentation to space indentation.

**Comment by mickaelistria** [comment]
OnTypeFormatting seems ideal (although it's not supported yet in LSP4E, so we'd have to add it, but it would be a good enhancement).
CodeActions are fine, but they require explicit user action, he I'd like things to happen by default as users type.
Another approach is to send some workspace/applyEdits from the server to the client.

**Comment by evidolob** [comment]
@mickaelistria Hm, maybe I miss understand the issue. You want to convert tab to space when user type it?

**Comment by mickaelistria** [comment]
@evidolob yes, exactly.

**Comment by evidolob** [comment]
OK, now I'm, rebasing #389 , I can add such conversion

**Comment by evidolob** [comment]
What we can do more on this, I think we can CodeAction to convert tabs in to space for existing files, as we generate error for tab character.

**Comment by mickaelistria** [comment]
I think having a codeaction to fix an error (whichever one) is always welcome!
