### ISSUE TITLE
Hovers escape markdown

### ISSUE THREAD

**Issue by felixfbecker** [redhat-developer/yaml-language-server#25]
I have this in a JSON schema:
```json
"working_directory": {
  "description":
    "In which directory to run the steps. (default: `~/project`. `project` is a literal string, not the name of the project.) You can also refer the directory with `$CIRCLE_WORKING_DIRECTORY` environment variable.",
  "type": "string",
  "default": "~/project"
},
```
Intead of rendering this as markdown, this is what the hover looks like:

![image](https://user-images.githubusercontent.com/10532611/33524142-f7ae8c04-d7cb-11e7-9d5e-5a4ada4a5165.png)

This is the hover result:

```js
[Trace - 01:47:59] Received response 'textDocument/hover - (21)' in 3ms.
Result: {
    "contents": [
        "In which directory to run the steps\\. \\(default: \\`~/project\\`\\. \\`project\\` is a literal string, not the name of the project\\.\\) You can also refer the directory with \\`$CIRCLE\\_WORKING\\_DIRECTORY\\` environment variable\\."
    ],
    "range": {
        "start": {
            "line": 3,
            "character": 4
        },
        "end": {
            "line": 3,
            "character": 21
        }
    }
}
```

Apparently the language server escapes the markdown

**Comment by JPinkney** [comment]
This behaves in the same way as vscode json where the language server escapes the markdown. According to json spec for [description](http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.1) it doesn't say it should be markdown (nor does it say it shouldn't) so its escaped. In the case of vscode json it looks like they added a custom field called markdownDescription. Heres the [vscode json discussion](https://github.com/Microsoft/vscode/issues/34498)

**Comment by gorkem** [comment]
@JPinkney Do we support `markdownDescription` on our schemas?

**Comment by JPinkney** [comment]
Yes we do. We have markdownDescription and markdownEnumDescriptions available.

**Comment by felixfbecker** [comment]
Are they exclusive? I would be worried about _only_ providing `markdownDescription` because probably not all clients support it
