### ISSUE TITLE
Tests fail when upgrading dependencies

### ISSUE THREAD

**Issue by apisim** [redhat-developer/yaml-language-server#251]
To reproduce:
```
$ git clone https://github.com/redhat-developer/yaml-language-server.git
...

$ cd yaml-language-server/

$ rm package-lock.json

$ rm yarn.lock

$ yarn install
...

$ yarn compile
yarn run v1.22.4
$ installServerIntoExtension ./out ./package.json ./tsconfig.json && tsc -p .
Copying package.json to extension's server location...
Updating server npm modules into extension's server location...

$ yarn test

(a slew of errors - 139 to be exact - that are _not_ the occasional timeout errors)
```

The important part is to remove/delete `yarn.lock` when using `yarn` instead of `npm`.

Similarly, set in package.json the version for "vscode-json-languageservice" to be "^3.5.2". Then run `yarn install` (or just `yarn`) followed by `yarn compile` and `yarn test`.

The errors fall loosely into six categories. Some of the fixes are needed due to breaking changes in "vscode-json-languageservice" since v3.3.0 (the version "yaml-language-server" seems to be using currently). For example, a function used to return in some cases `null` now returns `undefined` instead.

**Comment by JPinkney** [comment]
Can you submit a PR to fix this?

**Comment by apisim** [comment]
Created PR #252.
