### ISSUE TITLE
Defaults for didChangeConfiguration Messages

### ISSUE THREAD

**Issue by Trajamsmith** [redhat-developer/yaml-language-server#256]
Hey — we're trying to extend the functionality of [JupyterLab](https://github.com/jupyterlab/jupyterlab) to include all the features that language servers provide. At present, we're taking a look at server configuration messages. Right now, our `onDidChangeConfiguration` messages to a few server implementations are working well, but we're having small issues with the `yaml-language-server`.

We want our settings objects in the JupyterLab editor look something like this:
```json
{
    "language_servers": {
        "pyls": {
            "serverSettings": {
                "pyls.plugins.pydocstyle.enabled": true,
                "pyls.plugins.pyflakes.enabled": false,
                "pyls.plugins.flake8.enabled": true
            }
        },
        "r-languageserver": {
            "serverSettings": {
                "r.lsp.debug": true,
                "r.lsp.diagnostics": false
            }
        },
        "yaml-language-server": {
            "serverSettings": {
                "yaml.format.enable": true,
                "yaml.format.singleQuote": true
            }
        }
    }
}
```

We'd like to be able to send partial configurations like the above, but I _believe_ the issue we're having is that the `onDidChangeConfiguration` listener for the YAML server doesn't like partial configurations. 

My best guess is that this is because there are no defaults [here:](https://github.com/redhat-developer/yaml-language-server/blob/f6b89fdb9fedc1de38d6f7da42f0d09e92a41731/src/server.ts#L399)
```js
    if (settings.yaml) {
        yamlConfigurationSettings = settings.yaml.schemas;
        yamlShouldValidate = settings.yaml.validate;
        yamlShouldHover = settings.yaml.hover;
        yamlShouldCompletion = settings.yaml.completion;
        customTags = settings.yaml.customTags ? settings.yaml.customTags : [];

        if (settings.yaml.schemaStore) {
            schemaStoreEnabled = settings.yaml.schemaStore.enable;
        }
...
```

So if we send the configuration settings like I've written them up top, then the server turns off validation, even though my configuration object didn't mention validation.

Is that hunch correct? It's very possible that we're just looking at this the wrong way.

**Comment by JPinkney** [comment]
Yeah it looks like that's correct, partial configurations don't seem to be working correctly

**Comment by Trajamsmith** [comment]
May I submit a PR for this? This fixes the issue on my local:
```js
    // change this
    if (settings.yaml) {
        yamlConfigurationSettings = settings.yaml.schemas;
        yamlShouldValidate = settings.yaml.validate;
        yamlShouldHover = settings.yaml.hover;
        yamlShouldCompletion = settings.yaml.completion;
        customTags = settings.yaml.customTags ? settings.yaml.customTags : [];

    // to this
    if (settings.yaml) {
        yamlConfigurationSettings = settings.yaml.schemas || yamlConfigurationSettings;
        yamlShouldValidate = settings.yaml.validate || yamlShouldValidate;
        yamlShouldHover = settings.yaml.hover || yamlShouldHover;
        yamlShouldCompletion = settings.yaml.completion || yamlShouldCompletion;
        customTags = settings.yaml.customTags ? settings.yaml.customTags : [];
```

**Comment by JPinkney** [comment]
Yeah! A PR would be great!
