### ISSUE TITLE
Support for large schema files

### ISSUE THREAD

**Issue by shaded-enmity** [redhat-developer/yaml-language-server#26]
I have a JSON schema generated for Ansible modules to simplify writing of Ansible roles:

```
"yaml.schemas": {
  "/opt/ansible-schemas/": "ansible.json"
}
```
(you can find the file here https://raw.githubusercontent.com/shaded-enmity/ansible-schema-generator/master/examples/ansible.json and some example Ansible role here https://raw.githubusercontent.com/shaded-enmity/prototype/master/ansible_roles/docker/tasks/main.yml)

The problem is that the completion doesn't really work properly and I'm seeing suggestions that are out of context - for example the `state` key under `yum` is not suggested at all.

**Comment by JPinkney** [comment]
Out of curiosity which version of the extension are you on? I just tried doing auto completion underneath yum and was able to get state underneath it. All the items in [1] where able to autocomplete for me just fine. Do you have anymore examples by any chance?

[1] - https://raw.githubusercontent.com/shaded-enmity/prototype/master/ansible_roles/docker/tasks/main.yml

**Comment by shaded-enmity** [comment]
I'm on `0.0.7` - here's a [screencast](https://gfycat.com/gifs/detail/RegalCheeryGreatdane) of what is happening - `yum` gets completed properly, however when I start typing `name` I get a lot of suggestions from different modules (nagios, nova, nxos ..), and then the `state` key is not autosuggested at all.

**Comment by JPinkney** [comment]
It looks like there must be differences somewhere because even with that example on my machine it works fine. Also, with the schema it should be throwing an error (which it does in mine) because under yum name is supposed to be an array of strings. 

I'm not sure what would be causing this issue. I'm assuming there is another extension that is autocompleting the results such as 'nova_compute' and 'nove_keypair? Because according to the schema they aren't listed.

**Comment by JPinkney** [comment]
I think I may have found the issue, try doing

```
"yaml.schemas": {
       "ansible.json": "/opt/ansible-schemas/*.yaml"
}
```
or alternatively (This is what I was using to test)
```
"yaml.schemas": {
        "https://raw.githubusercontent.com/shaded-enmity/ansible-schema-generator/master/examples/ansible.json": "/opt/ansible-schemas/*.yaml"
}
```

**Comment by shaded-enmity** [comment]
Ha! I misunderstood the meaning of key/values here (to make matters worse, my file had `.yml` suffix), so I was probably just getting some contextual completion. Thanks!

Does the schema validation/lookup support the `anyOf` operator? I'm using it to distinguish between "command/shell/script" modules and the rest, example (notice how `shell` is now a key/value):

```
- name: Some other task
  shell: "echo $SOME_VAR"
  args:
    chdir: /root/some/directory
```
`shell` doesn't show up in the completion list, but after I type that the `args` section completes alright.

**Comment by JPinkney** [comment]
It does support the anyOf operator, i'm just looking into why its not behaving the expected way. Even with the json language server it doesn't give the correct completion results.

**Comment by shaded-enmity** [comment]
Currently in transit, I just realized that ‘oneOf’ would probably better reflect the semantics, gonna try when I get home.

**Comment by JPinkney** [comment]
AFAIK oneOf behaves the same way.

I believe whats happening is that because one of the anyOf objects only requires name when you only have name and nothing else its only auto completing from that object. However, if you type shell first for example you will get the correct result, same with args.

Out of curiosity I tried removing the other required ones in [this gist](https://gist.githubusercontent.com/JPinkney/dfe1e65c0ce867ebf557b13ea802a3c0/raw/d93d7c3bb9c07735566f4e91b4ad41e6b64c1bca/tester3.json) and it works.

**Comment by gorkem** [comment]
@shaded-enmity Is this working OK for you now, can we close it? I would be very much interested on the Ansible schema. Are you planning to make it available on schemastore.org?

**Comment by shaded-enmity** [comment]
@gorkem Yes, sorry, this is working.

I've generated a schema for Ansible 2.4 which can be found at https://github.com/shaded-enmity/ansible-schema-generator/blob/master/examples/ansible.json 

Good idea with schemastore.org, once I'm done with changes to support mutual exclusivity for aliases I'll generate schemas for various versions of Ansible and publish them there, thanks!

**Comment by languitar** [comment]
@shaded-enmity any news on getting the schema files onto schemastore? I'd like to use the one for 2.5 ;-)

**Comment by shaded-enmity** [comment]
@languitar Got derailed so many times by different stuff, but I guess that I could (finally) finish this tomorrow, I'll update here once I have something ready.

**Comment by languitar** [comment]
great, thanks!

**Comment by shaded-enmity** [comment]
@gorkem @languitar PTAL: Pending PR for SchemaStore with schemas for Ansible 2.0 through 2.5

**Comment by shaded-enmity** [comment]
And we're live :tada:  http://json.schemastore.org/ansible-stable-2.5

**Comment by ssbarnea** [comment]
Can someone give some hints on how to enable use of Ansible schema for all `roles/*` and `playbooks/*` folders? I think I managed to make it work but it would be great to have a generic example that people can just copy/paste.

Is there a way to know which scema was used on a specific file? Other plugins do expose information on the status bar.

Also, where should we report bugs regarding ansible json schema as I found one false positible regarding the use of `cacheable: true` inside set_facts, where we know very well the giving the boolean value is the correct way to do it.

**Comment by shaded-enmity** [comment]
@ssbarnea Please open issues/enhancements in https://github.com/shaded-enmity/ansible-schema-generator/ — the current schemas are meant to be used with `tasks/*` only, however it should be possible to make them work in a broader context of tasks directly "embedded" into roles/playbooks.
I'll take a look what I can do about `set_facts` in the meantime.

Thanks!
