### ISSUE TITLE
Unexpected Diagnostic Positions

### ISSUE THREAD

**Issue by trajamsmith** [redhat-developer/yaml-language-server#260]
Hey again!

We're running into some strange unexpected behavior surrounding the diagnostic positions since upgrading our project's dependency from `0.4.0 -> 0.8.0` (I know it's a pretty big jump).

These are the expected diagnostic positions when using `0.4.0`:
<img width="413" alt="Screen Shot 2020-05-23 at 11 32 56 AM" src="https://user-images.githubusercontent.com/11686766/82734559-a9e6a700-9ce9-11ea-8902-bb085c43dafa.png">

Upgrading to `0.8.0`, with no other changes at all, the diagnostic positions are no longer correct:
<img width="413" alt="Screen Shot 2020-05-23 at 11 35 48 AM" src="https://user-images.githubusercontent.com/11686766/82734571-c256c180-9ce9-11ea-8169-07d12f751260.png">

I'm poking around the server locally trying to figure out why this might be the case. 

For context, the content of the textDocument is: `greetings:↵    hello:↵    hello:↵`

**Comment by JPinkney** [comment]
It looks like duplicate key for some reason is 1 line off.  I _think_ something in here:
https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/yamlParser07.ts#L190-L205 is causing it

**Comment by trajamsmith** [comment]
I think you're right, I think it's specifically something here with the `convertError` function:
https://github.com/redhat-developer/yaml-language-server/blob/a9169daf6ac7c91273a53c72e322df0707c5e40b/src/languageservice/parser/yamlParser07.ts#L202

I'll do some more poking around and open a PR if I find a fix — if that's alright with you @JPinkney. Thanks for the prompt response!

**Comment by JPinkney** [comment]
@trajamsmith Yeah that works for me!

**Comment by trajamsmith** [comment]
Should be fixed with the #261 merge.
