### ISSUE TITLE
Add support for yamllint

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/yaml-language-server#262]
yamllint is a very popular linter for YAML and is already able to identify a wide range of issues.

Instead of increasing the complexity of language server with and reimplenenting all its checks it would make more sense to just make use of it.

This does not have to be a default option, it could be manually enabled by the user or by the presence of a `.yamllint` configuration file.

**Comment by JPinkney** [comment]
@gorkem WDYT? I still think it shouldn't be added as I said here: https://github.com/redhat-developer/vscode-yaml/issues/126#issuecomment-428745953 and it should instead just be a different extension

**Comment by gorkem** [comment]
I agree. A better approach would be to have yamlint operate on the same AST.

**Comment by ssbarnea** [comment]
Execution of yamllint is now provided by https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible extension.

**Comment by martydingo** [comment]
This extension is no longer available, and I can't believe that the official YAML plugin cannot support linting using `yamllint`, I would've thought the whole point of a YAML extension was partly for linting support.

**Comment by ssbarnea** [comment]
@martydingo Extension was renamed few years ago, current url is https://marketplace.visualstudio.com/items?itemName=redhat.ansible - ansible-lint embeds yamllint and can be used even if you do not have ansible code.

**Comment by martydingo** [comment]
@ssbarnea Okay that's fantastic.

I cannot get that to work though. I do have yamllint configured correctly, as other extensions do report errors (more specifically the [fnando.linter](https://marketplace.visualstudio.com/items?itemName=fnando.linter) extension). However both Ansible & YAML extensions do not report yamllint violations. 

How does one configure this extension to pick up on a .yamllint configuration file? I have not seen this specified in any of the extension settings.

**Comment by kemko** [comment]
> @martydingo Extension was renamed few years ago, current url is https://marketplace.visualstudio.com/items?itemName=redhat.ansible - ansible-lint embeds yamllint and can be used even if you do not have ansible code.

Most likely you are confusing [yamllint](https://www.npmjs.com/package/yaml-lint), which provides schema and syntax checking, and py-yamllint, which lacks schema checking but provides style checking.

**Comment by martydingo** [comment]
> Execution of yamllint is now provided by https://marketplace.visualstudio.com/items?itemName=redhat.ansible extension.

Could I ask what exactly was implemented? 

In the the extension documentation, it states:

`[Ansible Lint](https://ansible-lint.readthedocs.io/en/latest/) (required, unless you disable linter support; install without yamllint)`

Could this be elaborated on? 

I get *zero* lint violations from YAML or Ansible for non-Ansible violation (e.g. YAML violations). Practically there is zero linting happening on my inventory YAML files.
