### ISSUE TITLE
Receiving values added against property keys back as auto-complete suggestions

### ISSUE THREAD

**Issue by vardanbansal-harness** [redhat-developer/yaml-language-server#271]
Hi,

I'm using `yaml-language-server` package with `monaco-editor` and using below schema for auto-completion :

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    }
  }
}
```

On initial `control+space` editor hotkey, these are the options suggested by the `doComplete` api :

![image](https://user-images.githubusercontent.com/48940704/86784293-f5c59380-c07e-11ea-8e79-cbfc6a6447cb.png)

But after adding all the suggestions from above, if auto-complete is re-triggered on a new line, it starts showing values added against the property keys from the schema, such as `james`, `cameron` etc., also as suggestions, which are not even part of the above schema.

![image](https://user-images.githubusercontent.com/48940704/86784541-42a96a00-c07f-11ea-829c-3069358b779e.png)

Is this an expected behaviour?

**Comment by JPinkney** [comment]
Yes. Those values are shown because if monaco cannot find any completion items in the document it just shows all the keys/values

**Comment by vardanbansal-harness** [comment]
@JPinkney Thanks for confirming that. Is there a way/workaround to make monaco avoid doing this?

**Comment by JPinkney** [comment]
You'll have to turn off `wordBasedSuggestions`.
```
monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json",
    wordBasedSuggestions: false,
});
```
in the monaco editor playground stops it

**Comment by vardanbansal-harness** [comment]
Thanks @JPinkney ! Let me give it a try.

**Comment by vardanbansal-harness** [comment]
It did work @JPinkney ! Thanks for saving my day!

**Comment by vardanbansal-harness** [comment]
@JPinkney It did work. But there's one minor problem, it turns off all the value auto-suggestions as well. My use-case was more around restricting the values from showing up in property suggestions. 

Another weird issue that this change is causing is now conditional auto-suggestions don't seem to work. If you need, I can provide screenshots of auto-completion before and after this change.

**Comment by JPinkney** [comment]
You'll probably have to dig into the monaco api documentation to figure out exactly the settings you need: https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html I'm not actually all that familiar with the monaco api, I only know a few things

**Comment by JPinkney** [comment]
I'm going to close this as its monaco's behaviour and not anything we can do from our side
