### ISSUE TITLE
Allow absolute paths to be specified in yaml.schemas

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/yaml-language-server#275]
[Project relative paths requirement](https://github.com/redhat-developer/yaml-language-server#associating-a-schema-to-a-glob-pattern-via-yamlschemas) for specifying `yaml.schemas` is probably a suitable way to deal with VSCode, but definitely not for others.

We suggest to allow using an absolute path for a schema, so, when resolving a schema content, if no project is found or path doesn't resolve against project, it should be attempted to be resolved as absolute path. 
This would allow plain yaml edition to work without a project, which is actually not so unusual.

Related issue: https://github.com/eclipse/wildwebdeveloper/issues/461

**Comment by JPinkney** [comment]
Does doing something like:
```
"yaml.schemas": {
    "file:///home/johnd/some-schema.json": ["some.yaml"]
}
```
or
```
"yaml.schemas": {
    "/Users/johnd/some-schema.json": ["some.yaml"]
}
```
not work?

It would be strange that it works on vscode but not on eclipse. Can you let me know what the didChangeConfiguration request is on eclipse side

**Comment by vrubezhny** [comment]
@JPinkney Any use of an absolute path to a schema results into a set of messages like described in https://github.com/eclipse/wildwebdeveloper/issues/461#issuecomment-656270205. The same is true for trying to use of URL like `file:///home/user/ws/project/...`to a schema.
The only project relative path works here or URL pointing to a `http://...`

**Comment by JPinkney** [comment]
Can you try upgrading to 0.9.0 and see if it still occurs?

**Comment by vrubezhny** [comment]
@JPinkney Upgrade to YAML LS 0.9.0 is ongoing. I'll try reproducing it using version 0.9.0 this week.

**Comment by JPinkney** [comment]
@vrubezhny Were you able to test it with the newest version to see if this issue still occurs?

**Comment by ssbarnea** [comment]
This bug should be closed because I am using absolute paths for months and they do work quite well. The trick is to use `file://` URI which allow only full paths (3 slashes).
