### ISSUE TITLE
Include eslint checks in build cycle

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#278]
Now we have 

```
✖ 84 problems (21 errors, 63 warnings)
  21 errors and 0 warnings potentially fixable with the `--fix` option.
```

eslint errors/warnings. 

Need to fail build if PR doesn't not follow codestyle.

**Comment by JPinkney** [comment]
Yeah, we recently switched from tslint to eslint thats why theres so many. I agree, we should add this in. I'm currently re-doing the tests to massively improve them so I can fix up any eslint errors in that folder

**Comment by evidolob** [comment]
@JPinkney Is any reason to use custom rules for eslint? We can consider to use `@typescript-eslint/eslint-recommended` and `@typescript-eslint/recommended` with some modifications. They are pretty good and commonly used for TS projects.

**Comment by JPinkney** [comment]
I'm fine with using @typescript-eslint/recommended if other projects are using it too

**Comment by evidolob** [comment]
Yes, that recommended by [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#configuration).

**Comment by evidolob** [comment]
@JPinkney Another question is two or four space indentation? 
It is more common for JS/TS projects to use two, but most people from Java/C# world prefers four.
A few links:

- https://javascript.info/coding-style
- https://google.github.io/styleguide/jsguide.html#formatting-block-indentation
- https://standardjs.com/rules.html
- https://www.reddit.com/r/javascript/comments/5rjrcy/why_is_twospace_tab_indent_becoming_the_standard/

WDYT?

**Comment by JPinkney** [comment]
I think we should probably go with what the JS/TS community uses, so probably 2
