### ISSUE TITLE
Automatic linking of Camel K schema based on Camel K modeline

### ISSUE THREAD

**Issue by apupier** [redhat-developer/yaml-language-server#279]
Camel K has a specific modeline which allows to identify that a yaml file is a Camel K one.

```
# camel-k:
```

They would like to avoid forcing a specific filename (such *.camelk.yaml).

Given that schema cannot be specified inside the file directly. Would it be possible to associate the Camel K schema with files using the modeline `# camel-k`?

technically, it would be a "simple" matter of modifying https://github.com/redhat-developer/yaml-language-server/blob/3cdc18b4329eea9facf336bb21c3fda72d139a2a/src/languageservice/services/yamlSchemaService.ts#L217

From a conceptual point of view, are we ready to have specific code to Camel K in Yaml language server? (there is already specific code for Kubernetes)

this would be last priority for schema resolution https://github.com/redhat-developer/yaml-language-server/issues/250#issuecomment-658824247

**Comment by JPinkney** [comment]
Personally I'm against having specific code for any extension inside of the language server, and instead, want everything to be an API if possible. The only reason why there is kubernetes specific code was that when I was assigned the project ~3 years ago it was originally just a language server for kubernetes files. Eventually, we enhanced everything to include YAML but also kept kubernetes for compatibility.

@gorkem WDYT?

**Comment by gorkem** [comment]
I agree. I would rather have APIs. I am not sure even kubernetes is making a lot of sense anymore, there are extensions out there nowadays that are using the APIs to set k8s schemas better than the fixed setting. It is something that is left over from the early days of the extension.

**Comment by apupier** [comment]
> Personally I'm against having specific code for any extension inside of the language server

me too personally.

> there are extensions out there nowadays that are using the APIs to set k8s schemas better than the fixed setting

the problem with this approach is that it requires a specific implementation in each client.

> want everything to be an API if possible.
> I would rather have APIs.

would be an API to provide a custom "SchemaResolver" written in javascript/TypeScript? How to pass it when the client is not a typescript project? a npm module and the class name?
it would mean that each clien twoudl need to provide it also. But we would have to write the "SchemaResolver" a single time.

**Comment by apupier** [comment]
> > want everything to be an API if possible.
> > I would rather have APIs.
> 
> would be an API to provide a custom "SchemaResolver" written in javascript/TypeScript? How to pass it when the client is not a typescript project? a npm module and the class name?
> it would mean that each clien twoudl need to provide it also. But we would have to write the "SchemaResolver" a single time.

the `CustomSchemaProvider` is already available for that? https://github.com/redhat-developer/yaml-language-server/blob/3cdc18b4329eea9facf336bb21c3fda72d139a2a/src/languageservice/services/yamlSchemaService.ts#L75

https://github.com/redhat-developer/yaml-language-server/blob/3cdc18b4329eea9facf336bb21c3fda72d139a2a/src/languageservice/services/yamlSchemaService.ts#L244-L269

**Comment by JPinkney** [comment]
If we re-used the custom schema provider I think what we could do is modify it so that if something like:
```
# some_modeline 
```
appears in the YAML file then instead of passing in the resource to the customSchemaProvider pass in the modeline. That way any extensions that handle the modeline would pass the schema back.

For example,
If we have vscode apache camel and vscode-yaml installed. vscode apache camel would set up the the client side part of the custom schema provider to say if we are passed `camel-k` then return the camel schema. Then when the modeline is passed in it automatically resolves the schema

**Comment by apupier** [comment]
I started work to register a customSchemaProvider https://github.com/camel-tooling/vscode-camelk/pull/483

Sometimes the schema is correctly found and the completion is provided but most of the time not. Currently searching why.

**Comment by apupier** [comment]
rejected to avoid having Camel K specific code inside Yaml language Server.
