### ISSUE TITLE
Provide hover and other services even on partially-invalid YAML

### ISSUE THREAD

**Issue by alexkreidler** [redhat-developer/yaml-language-server#285]
The VSCode guide for implementing language servers [states that](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#error-tolerant-parser-for-language-server) parsers should be error tolerant, i.e. do the best to parse even partially invalid code or configuration.

![Peek 2020-07-18 02-26](https://user-images.githubusercontent.com/11166947/87846478-2e931300-c89e-11ea-8a21-157845b8093e.gif)

**Comment by JPinkney** [comment]
I think this is more just an issue where the YAML does not find any matching subschemas for the file. The kubernetes schema uses a custom comparator that is more strict then the regular JSON schemas passed into the extension.

My guess (and my testing) has shown that this can only be reproduced with the kubernetes schema so far and hasn't yet been reproduced with any other schema yet.

**Comment by apupier** [comment]
Kubernetes registered schema provider is not error-tolerant. it needs to be fixed in VS Code Kubernetes.
