### ISSUE TITLE
Error in 'YAMLSchemaService' when file pattern association provided

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#294]
The problem in https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlSchemaService.ts#L235 , `FilePatternAssociation` class doesn't have `getURIs` method, replacing with `getSchemas` solve the error, but I'm not sure if there is better solution or why that 
`getURIs` calls there. As [FilePatternAssociation](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlSchemaService.ts#L47) has only `getSchemas`, but most recent `vscode-json-languageservice` in [FilePatternAssociation](https://github.com/microsoft/vscode-json-languageservice/blob/master/src/services/jsonSchemaService.ts#L112) has  `getURIs`. I'm not sure how that bot classes are related. 
Is using  `getSchemas` instead of `getURIs` are good?

**Comment by JPinkney** [comment]
yamlSchemaService mostly extends the jsonLanguageService except for a few select classes that need to be copied over. Most likely what needs to happen is FilePatternAssociation needs to be copied over again and then it should be fine. We should be using getURIs to stay inline with the jsonLanguageService

**Comment by evidolob** [comment]
@JPinkney It is something strange there, when I use `getURIs` I got:

```
[Error - 2:52:08 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: entry.getURIs is not a function or its return value is not iterable
  Code: -32603 
```

But when I use `getSchemas`, I have failing tests, but my scheme is working.
I provide file mappings in project configuration:
```json
  "yaml.schemas": {
    "./.vscode/test.json": ["test.yaml"]
  }
``

**Comment by apisim** [comment]
That is why `this.filePatternAssociations` is of type [JSONSchemaService.FilePatternAssociation[]](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlSchemaService.ts#L81) is and not [FilePatternAssociation](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlSchemaService.ts#L47)[]. 

If I recall, [FilePatternAssociation]((https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/yamlSchemaService.ts#L47)) couldn't be just removed. It has something to do with the special processing for Kubernetes?

**Comment by JPinkney** [comment]
Yeah it looks like its only used to check when the current file matches the schema path for kubernetes specifically

**Comment by evidolob** [comment]
Hm, it seems that it was in my local environment, for some reason whole `node_modules` was copied in to `out` directory, and it contains very old `vscode-json-languageservice`. I think we need to clean up `out` during build.
