### ISSUE TITLE
Add schema info to diagnostics

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/yaml-language-server#310]
when validation against a schema fails also add the schema information to the published diagnostics. This way users can identify the schemas that is affecting their YAML files.

**Comment by evidolob** [comment]
@gorkem @JPinkney 
I have prototype of this, I add scheme URL in `source` field of `Diagnostic`
Example URL:
<img width="1085" alt="Screenshot 2020-09-24 at 14 52 36" src="https://user-images.githubusercontent.com/929743/94141844-0ca5a600-fe76-11ea-8552-31403b20b69b.png">
Example local file:
<img width="1085" alt="Screenshot 2020-09-24 at 14 53 02" src="https://user-images.githubusercontent.com/929743/94141922-2646ed80-fe76-11ea-86be-7de7a44daa21.png">

WDYT?

**Comment by JPinkney** [comment]
That looks good to me

**Comment by gorkem** [comment]
Are you sending it as part of the message filed on `Diagnostic`?

**Comment by evidolob** [comment]
I not sure that understand the question, I add URL/path to [Diagnostic#source](https://code.visualstudio.com/api/references/vscode-api#Diagnostic) field

**Comment by gorkem** [comment]
That is exactly what I was asking. 
Can you also provide a screenshot the problem view when you have one of these issues.

**Comment by evidolob** [comment]
<img width="1140" alt="Screenshot 2020-09-28 at 10 28 25" src="https://user-images.githubusercontent.com/929743/94402928-5abbf180-0175-11eb-94e0-e9606aafc1ce.png">

**Comment by gorkem** [comment]
OK this is half bad :) Can we have a format such as `yaml-schema: ${schema}` and for generic yaml issues just `yaml`

**Comment by evidolob** [comment]
We can, but what is the value of `${schema}` ? URI or just name?
We can use schema `title` if present, if not, than URI.

**Comment by gorkem** [comment]
> We can use schema `title` if present, if not, than URI.
+1 Sounds like a plan

**Comment by rivy** [comment]
Thanks, nice addition!

**Comment by ssbarnea** [comment]
I looked for the entire morning on how to expose this information and I still do not know how to enable the diagnosticst. Was this fixed only in an unreleased version? -- I am currently using the latest YAML 0.15.0 extension, which was released two weeks ago, so I expect to be able to see the diagnostics.  Is there a hidden option to enable these?

**Comment by evidolob** [comment]
@ssbarnea this works since `0.12.0`

**Comment by ssbarnea** [comment]
@evidolob So why do I see only this:
![](https://sbarnea.com/ss/Screen-Shot-2021-02-23-12-45-01.36.png)

**Comment by evidolob** [comment]
I discuss that there https://github.com/redhat-developer/yaml-language-server/issues/310#issuecomment-700514331 
Becouse your schema has `title` field we show it first and then show shema url.

**Comment by evidolob** [comment]
And you can use `Jump to schema location` CodeAction to open schema in editor.

**Comment by ssbarnea** [comment]
The string that is displayed is not really the schema name but is the title of the schema property that generated the error, which does not give any hint about which schema was effectively used. Take a look at one file like https://github.com/ansible-community/ansible-lint/blob/schemas/src/ansiblelint/data/ansible-playbook-schema.json and you will see lots of titles around.

So yet, we do display information from within the schema but not the schema information itself.

Combined with the fact that user can enable the schemaStore, you endup with a plethora of possible sources for schemas, some configured by local patterns and some determined by the schemastore. Still, as a user I have no clue from which file this came.

I am not sure where is the "Jump to schema location" available from, as by pressing F1 (CommandPallete) I am unable to find it and I neither see the light-bulb contextual action available on the error, as documented on https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings -- (i did not disable it in settings).

My yaml related settings look like:
```
  "yaml.completion": true,
  "yaml.customTags": [
      "!include-raw:"
  ],
  "yaml.format.enable": true,
  "yaml.schemas": {
...
  },
  "yaml.schemaStore.enable": false,
  "yaml.trace.server": "verbose",
  "yaml.validate": true
```

**Comment by evidolob** [comment]
Oh, my bad `Jump to schema location` is not released yet.

As for 
> The string that is displayed is not really the schema name but is the title of the schema property that generated the error, which does not give any hint about which schema was effectively used. Take a look at one file like https://github.com/ansible-community/ansible-lint/blob/schemas/src/ansiblelint/data/ansible-playbook-schema.json and you will see lots of titles around.

>So yet, we do display information from within the schema but not the schema information itself.

>Combined with the fact that user can enable the schemaStore, you endup with a plethora of possible sources for schemas, some configured by local patterns and some determined by the schemastore. Still, as a user I have no clue from which file this came.

Can you create an issue for it? We can fix that pretty fast.
