### ISSUE TITLE
Error when file has "Type" attribute --- yamlValidation

### ISSUE THREAD

**Issue by caobincb** [redhat-developer/yaml-language-server#317]
Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'type' of undefined
  Code: -32603

**Comment by evidolob** [comment]
@caobincb Can you provide yaml sample on witch you has that error?

**Comment by GhostLyrics** [comment]
Create the following folder file as `roles/example/tasks/main.yml` to simulate using Ansible and open the top level folder with e.g. Visual Studio Code with yaml-language-server enabled:

```
---
- 
```

After typing the list indicator, type any string and you'll get the error message for every key you hit. Example:

```
---
- na
```

Result:
```
[Error - 8:34:51 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'type' of undefined
  Code: -32603 
```

**Comment by bendem** [comment]
Thanks god for that fix ❤️
