### ISSUE TITLE
Do not return hover info if description is not available

### ISSUE THREAD

**Issue by bhsubra** [redhat-developer/yaml-language-server#320]
We are getting results back on hover request even if contents is empty. This would require IDEs to add a check to not render it.  Range without contents is not useful. Should the language server return null if description is not available?

Message:
{
  "jsonrpc": "2.0",
  "id": 46,
  "result": {
    "contents": [
      ""
    ],
    "range": {
      "start": {
        "line": 6,
        "character": 0
      },
      "end": {
        "line": 6,
        "character": 8
      }
    }
  }
}

**Comment by ssbarnea** [comment]
IMHO, hover should return "title" when "description" is unavailable. At this moment I did see it returning only the title.

**Comment by gorkem** [comment]
Did #500 also fix this one? I am closing, please let me know if it is not fixed for you.
