### ISSUE TITLE
clientSnippetSupport field in server.ts is unused

### ISSUE THREAD

**Issue by rcjsuen** [redhat-developer/yaml-language-server#33]
It's not clear to me what this field is for. It gets initialized by reading the client's `textDocument.completion.completionItem.snippetSupport` capability but is then never read or used.

https://github.com/redhat-developer/yaml-language-server/blob/d332a84b6ab2e681140cf4bb2827cb8e67a39737/src/server.ts#L63-L91

**Comment by JPinkney** [comment]
From what I remember this was when we were porting things from https://github.com/adamvoss/vscode-yaml-languageservice. Originally, the owner of that repository was going to shut down his vscode extension and then redirect the traffic to us but he wanted to make sure all his users were supported as well. He ended up leaving his extension up but we still have lingering code from his repository in ours.

**Comment by rcjsuen** [comment]
I found the exact same code in the other language server so I opened adamvoss/vscode-yaml#20.

**Comment by JPinkney** [comment]
The removal was merged into master so i'm going to close this
