### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by allanadair** [redhat-developer/yaml-language-server#335]
### Is your enhancement related to a problem? Please describe.

I am not a JavaScript or TypeScript developer and it would be nice to have a usable implementation of the yaml-language-server provided in the form of a Docker image.

### Describe the solution you would like

I would like to see a Dockerfile added to the project which provides an image that has the yaml-language-server installed and configured with a set of common defaults.

### Describe alternatives you have considered

I have considered packaging yaml-language-server for my particular use case outside of the Docker context, but it became a particularly daunting task. I decided that creating a Dockerfile for myself would be a good option, but may be best handled by the yaml-language-server code contributors.

### Additional context

Many users may not desire to have the node toolchain installed on their machines and would just like to have an option to run a containerized implementation of the language server.

**Comment by urohit011** [comment]
I would like to take this up.

**Comment by gorkem** [comment]
@urohit011 Feel free to issue a Pull Request when you can
