### ISSUE TITLE
Semantic Tokens support

### ISSUE THREAD

**Issue by eeshugerman** [redhat-developer/yaml-language-server#338]
### Is your enhancement related to a problem? Please describe.

Yes, but it's a problem specific to Emacs: the YAML syntax highlighting provided by [`yaml-mode`](https://github.com/yoshiki/yaml-mode) is buggy because, [in the author's words](https://github.com/yoshiki/yaml-mode/blob/master/yaml-mode.el#L58-L60), "YAML ... is complex to parse, and this mode doesn't even really try". 

### Describe the solution you would like

I'd greatly appreciate it if `yaml-language-server` supported [Semantic Tokens](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens). Emacs' [`lsp-mode`](https://github.com/emacs-lsp/lsp-mode) supports Semantic Tokens as of v7.0, so, if I'm not mistaken, if `yaml-language-server` added support, then proper YAML syntax highlighting in Emacs could be a reality.

### Describe alternatives you have considered

An alternative would be to write a new Emacs mode that actually parses YAML. If I wanted to learn elisp in depth I'd consider taking a stab at this, but I don't, and I'd be reinventing the wheel anyway.

**Comment by gorkem** [comment]
depends on #442

**Comment by eeshugerman** [comment]
Now that treesitter is a thing I'm not really interested in this anymore, so I'm gonna close it. Feel free to reopen.
