### ISSUE TITLE
Is there a way to find a definition in other file on the `"$ref": ...`

### ISSUE THREAD

**Issue by kyoh86** [redhat-developer/yaml-language-server#339]
## Summary

I want to jump to other file with using the "Goto Definition" on the "$ref".

For example:

openapi.yaml:

```yaml
openapi: "3.0.3"
paths:
  /user:
    get:
      parameters:
        - $ref: "./paging.yaml#/components/parameters/offset"
```

paging.yaml:

```yaml
openapi: "3.0.3"
components:
  parameters:
    name: parameters
    schema:
      type: string
```

When I request "Goto Definition" for the "./paging.yaml#/components/parameters/offset", yaml-language-server says that the definitions are not found.

Is there a way to find the definition?

**Comment by JPinkney** [comment]
Currently `Goto Definition` only works inside of the same file

**Comment by kyoh86** [comment]
Thanks, I see.
Would you plan to make it works with other files?

**Comment by JPinkney** [comment]
This feature actually calls a method from https://github.com/microsoft/vscode-json-languageservice to do it so once it's supported there we will automatically get it here

**Comment by kyoh86** [comment]
I see. thank you!
