### ISSUE TITLE
Local schema changes are not reflected in real-time

### ISSUE THREAD

**Issue by Fannon** [redhat-developer/yaml-language-server#34]
First thank you for creating this extension / language server!

I've noticed one problem in my particular usecase. 
There I'm using JSON Schema definitions which are available locally. In case of VSCodes default JSON implementation, when the local Schema updates, the affected JSON files get re-evaluated and immediately reflect the updated Schema.

The yaml-language-server seems to cache those local schemas. I need to restart the VSCode (i guess the language-server really) to get the Schemas reloaded.

Best,
Simon

**Comment by JPinkney** [comment]
Hmm, I've never had this issue before, its always worked for me but I'll look into it.

**Comment by Fannon** [comment]
Thanks! 
This happened, when using workspace settings defining which schemas match.

If it would be helpful for you, I could create a small project reproducing this situation.

**Comment by JPinkney** [comment]
@gorkem I have opened a PR for this issue on the vscode-yaml side (https://github.com/redhat-developer/vscode-yaml/pull/53) but I'm not sure if this is the best way to do this. Basically what is happening is the language server only sees the version of the json schema when it is inserted into the server via the onDidChangeConfiguration. However, when a user is editing the schema the changes aren't reflected in real time. By watching all json files we by consequence also watch the json schemas in the workspace, thus fixing the issue.

**Comment by JPinkney** [comment]
Should be fixed as of our 0.0.8 release!
