### ISSUE TITLE
Issue with UI5 YAML  in 0.12.0

### ISSUE THREAD

**Issue by AlexanderDemidovich74** [redhat-developer/yaml-language-server#344]
## Describe the bug
No completion for https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

It works in version 0.11.1 in VSCode (though, not completely).  Now the only first object specVersion is suggested...
ajv-cli validates the project's ui5.yaml against this schema without any problems.

## Expected Behavior
Completion support (ctrl+space)

## Environment
VS Code.

**Comment by evidolob** [comment]
@AlexanderDemidovich74 This bug may be fixed with https://github.com/redhat-developer/yaml-language-server/pull/357 as ui5 schema use `if/then/else` conditions. Can you verify?

**Comment by evidolob** [comment]
Fille free to reopen this if you still has a problem
