### ISSUE TITLE
Inconsistent way to generate whole property snippet and value snippet, when it contains \"

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/yaml-language-server#353]
Given that I have this property:
``` json
"properties": {
  "property1": {
    "type": "string",
    "default": "\"mydefault\""
  }
}
```

If I write `property1: ` and ask completion (Ctrl+tab), then choose first option, I get this generated:
`property1: "mydefault"`
That is nice.

But if I write `property1` and ask completion (Ctrl+tab), then I get this generated:
`property1: \"mydefault\"`

So the second case is inconsistent and is an issue.
Could you fix it?

**Comment by fbaligand** [comment]
Hi,

I just tried YAML extension v0.18.0, and unfortunately, I still reproduce the issue :(
So can you reopen this issue?

**Comment by evidolob** [comment]
@fbaligand Sure, that strange. Can you share schema where you have this?

**Comment by fbaligand** [comment]
Hi @evidolob,

Thanks for reopening the issue.

My test schema to reproduce this issue is exactly the schema I provided in issue description.
The whole schema is:
``` json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"property1": {
			"type": "string",
			"default": "\"mydefault\""
		}
	}
}
```

**Comment by fbaligand** [comment]
That said, to reproduce the issue, all characters are important:
- *If I write `property1: ` and ask completion (Ctrl+tab)* => there is a space after ":"
- *But if I write property1 and ask completion (Ctrl+tab)* => no ":" at end

**Comment by fbaligand** [comment]
@evidolob 
Thanks for the fix!
Is there a (easy) way to try the fix before next release?

**Comment by evidolob** [comment]
@fbaligand Yes you can follow this https://github.com/redhat-developer/vscode-yaml/blob/master/CONTRIBUTING.md#developing-the-client-and-server-together to build and run
