### ISSUE TITLE
completionHelper will break yaml file if it contains \r charactor

### ISSUE THREAD

**Issue by andxu** [redhat-developer/yaml-language-server#37]
Here is the code to repro the test 
<pre>
let content = "test\r\nfoo:bar\r\n";
let position = 3;
let testTextDocument = TextDocument.create("file://~/Desktop/vscode-k8s/test.yaml", "yaml", 0, content);
let res = completionHelper(testTextDocument, testTextDocument.positionAt(position), false);
console.log(JSON.stringify(res.newText));
</pre>

The test has output of "test\r:\r\no:bar\r\n" (foo has been cut off first two charactors 'fo'

**Comment by rcjsuen** [comment]
I can reproduce this problem but it seems to me like that function isn't really intended to be API.

Why are you calling this function instead of using the language service anyway, @andxu?

**Comment by andxu** [comment]
I am using the yaml language server in vscode-yaml extension, I found some completions are not right so I take a look at the code and found it is caused by \r, so I opened an issue here, and I will open a PR to fix it.

**Comment by JPinkney** [comment]
Thanks for the PR!
