### ISSUE TITLE
Relative path in inline schema

### ISSUE THREAD

**Issue by EmilSodergren** [redhat-developer/yaml-language-server#371]
## Summary
I have tried to use the inline syntax to specify a schema file for my yaml. The schema file is in the same directory as the yaml.
I have tried to use:
  `# yaml-language-server: $schema=./schema.yaml`
and
  `# yaml-language-server: $schema=/path/from/.git/folder/schema.yaml`

but it does not seem to work.

Is this supposed to be possible?

**Comment by JPinkney** [comment]
Currently, it just supports a url to the schema: `# yaml-language-server: $schema=<urlToTheSchema>` but I can take a look into supporting local files as well. It shouldn't be too difficult

**Comment by EmilSodergren** [comment]
It works if i give the full path to the file /home/<user>/workspace/...

**Comment by jamesramsay** [comment]
@JPinkney I too ran into this issue. Do any functions/areas come to mind where you suspect the issue might be? It wasn't  obvious to me why the relative path handling in `src/languageservice/services/schemaRequestHandler.ts` wouldn't kick in.

**Comment by JPinkney** [comment]
Off the top of my head its probably because you can't get the workspace root from the yamlSchemaService. I have a PR open that does a big refactoring and should make it possible

**Comment by ssbarnea** [comment]
This is problematic because I am writing the schema itself in my repository and I want to enable vscode to lint my own examples and see if they pass or fails. How am I supposed to validate them before I merge the code and push it?

**Comment by SamB** [comment]
> Off the top of my head its probably because you can't get the workspace root from the yamlSchemaService. I have a PR open that does a big refactoring and should make it possible

Why would you want the workspace root? Shouldn't this be relative to the file containing `# yaml-language-server: $schema=./schema.yaml`?

**Comment by ssbarnea** [comment]
Yaml files can be placed almost anywhere in the source tree while the user may need to use a schema that is unique to a repository. Relative to current file is useless unless you store these files in only one folder, but relative to git/scm repo makes it valid for any file within the repo.

**Comment by EmilSodergren** [comment]
If you use the full path from system root it is valid for all files on your computer. If the competition is about reaching the "maximum validity" with one line.  That is possible today but completely beside the point of this enhancement proposal. This ticket is about pointing to a schema with a known relative path. Do not involve version control. File and schema are not neccessarily in the same repository.

**Comment by bayerlse** [comment]
Hey there! 👋 
Any update on this issue?
I also would need to reference the schema (via relative path) inline.

**Comment by derba** [comment]
Helm, the leading cloud native application delivery and configuration management solution, packs yaml and other files in a [well defined structure](https://helm.sh/docs/topics/charts/#the-chart-file-structure). Among those values.yaml and [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) in the same directory.
It seems logical to start values.yaml with this line:
`# yaml-language-server: $schema=./values.schema.json`
