### ISSUE TITLE
Array indentation in autocomplete is broken after upgrade to 0.13

### ISSUE THREAD

**Issue by yazaabed** [redhat-developer/yaml-language-server#376]
Hallo everyone! I hope you are having a good time! 

We have upgraded our implementation on top of yaml-language-server to latest version. And after successfully finish all needed things, we noticed that the array required fields autocomplete is broken. After debugging we found out that it is because of a small change in the completion service [here](https://github.com/redhat-developer/yaml-language-server/blob/b9fda68469a775253aaa4d507e8d56f5d749baaa/src/languageservice/services/yamlCompletion.ts#L803) and the code was changed to [this](https://github.com/redhat-developer/yaml-language-server/blob/b9b52253b93d460e1928da8e5c553f6cfcb0316f/src/languageservice/services/yamlCompletion.ts#L776)

Can you please give us a way to fix this issue? Or is it a bug from your side?

Thank you and Best regards!

**Comment by JPinkney** [comment]
Do you have any particular schema and yaml that can reproduce the issue? I've just tried on VSCode with:
```
sample:
  - name: test
    email: test
    homepage: test
    role: test
``` 
and
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "name": "Package",
    "type": "object",
    "properties": {
        "sample": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "email",
                    "homepage",
                    "role"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "homepage": {
                        "type": "string"
                    },
                    "role": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```
and haven't been able to reproduce yet

**Comment by yazaabed** [comment]
Yes for first level array it is working fine but for nested arrays it is not working in the new version. For example we have this yaml.

```
components:
  - id: jsakdh
    type: list
    settings:
        data:
          arrayItems:
            - show: true
        id: asdgjajkdg <- this id here should be autocompleted under show not under data.
```

Schema
```
{
    "type": "object",
    "properties": {
        "components": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "settings": {
                        "type": "object",
                        "properties": {
                            "data": {
                                "type": "object",
                                "properties": {
                                    "arrayItems": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "required": [
                                                "id"
                                            ],
                                            "properties": {
                                                "show": {
                                                    "type": "boolean",
                                                    "default": true
                                                },
                                                "id": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by JPinkney** [comment]
Strange, I've just tested it on VSCode and everything is working as expected. Is this for monaco-yaml? If so I'll have to go in and test why it's behaving differently then VSCode

**Comment by yazaabed** [comment]
> Strange, I've just tested it on VSCode and everything is working as expected. Is this for monaco-yaml? If so I'll have to go in and test why it's behaving differently then VSCode

No Monaco-yaml didn't upgrade to latest language server yet. This is a custom yaml language worker within the company I am working with. It is the same implementation in Monaco-yaml, but with language server 0.13.

The one in monaco-yaml is 0.11.0.

**Comment by yazaabed** [comment]
@JPinkney when I downgraded to 0.11 the issue is fixed. So I believe it is the recursive nested array.

**Comment by yazaabed** [comment]
@JPinkney here is a screenshot of the items returned from the completion service.

![Screenshot 2020-12-15 at 14 40 58](https://user-images.githubusercontent.com/8734097/102222366-9f893600-3ee3-11eb-8000-93614e6f3beb.png)

**Comment by evidolob** [comment]
@JPinkney I think it may be related to my changes in https://github.com/redhat-developer/yaml-language-server/pull/332
I will give a look on this.

**Comment by evidolob** [comment]
Hm, @yazaabed I test your schema and completion works for me:
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/929743/102227603-6e643200-3ef2-11eb-801f-f93093bf50a3.gif)

**Comment by yazaabed** [comment]
You need to do the autocomplete from the settings level not down. Please check the gif down.

![Dec-15-2020 16-15-02](https://user-images.githubusercontent.com/8734097/102233649-c863f800-3ef0-11eb-95ff-0570104c456a.gif)

**Comment by evidolob** [comment]
OK, we definitely has a bug with completion:
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/929743/102235567-209ff780-3efb-11eb-8d42-cfb9691ad0d3.gif)
We add unneeded `  `  after settings completion, and for some reason not providing template for rest objects

**Comment by yazaabed** [comment]
@evidolob thank you for your response. What we can do to fix it? Should I go back to the previous version? It will take time to go back because we removed most of the things. And new things like calculate links.

**Comment by evidolob** [comment]
@yazaabed I provide PR to fix this ASAP, we plan to release `0.14.0` on next week, so it up to you.

**Comment by evidolob** [comment]
Just FYI, I was able to reproduce this issue with :
```json
{
    "type": "object",
    "properties": {
        "components": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "settings": {
                        "type": "object",
                        "required": ["data"],
                        "properties": {
                            "data": {
                                "type": "object",
                                "required": ["arrayItems"],
                                "properties": {
                                    "arrayItems": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "required": [
                                                "id"
                                            ],
                                            "properties": {
                                                "show": {
                                                    "type": "boolean",
                                                    "default": true
                                                },
                                                "id": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

```

**Comment by yazaabed** [comment]
> @yazaabed I provide PR to fix this ASAP, we plan to release `0.14.0` on next week, so it up to you.

Yeah it can wait, we will not release before next week. Thank you for your update.

**Comment by yazaabed** [comment]
@evidolob I can help testing it locally with my schema. I will branch out from your branch and check.

**Comment by yazaabed** [comment]
@evidolob Yes! It is working fine. Thank you 👍 

![test](https://user-images.githubusercontent.com/8734097/102337267-8ee3c900-3f92-11eb-9774-7e64febd8041.gif)

**Comment by evidolob** [comment]
@yazaabed Can you add comment in to #379 ?

**Comment by yazaabed** [comment]
> @yazaabed Can you add comment in to #379 ?

Sure!
