### ISSUE TITLE
Mocha test interface misusing

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#398]
### Is your enhancement related to a problem? Please describe.
Currently we use mocha test interface in not wholly way. We run tests with `--ui tdd` parameter, which mean using [TDD](https://mochajs.org/#tdd), but we declare test with `it` instead of `test` and use `before`/`after` for test setup, instead of `setup`/`teardown`. Such misusing may cause test fail, because `before`/`after` hooks may be called in wrong context, for different file.

### Describe the solution you would like
I would like to fix all test to use TDD or BDD interface

### Describe alternatives you have considered
As alternative we may switch to [Jest](https://jestjs.io/) as our test framework

**Comment by gorkem** [comment]
No idea how we managed to do this :) Just pick one and go with it.
