### ISSUE TITLE
Upgrade to newer vscode-json-languageservice

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/yaml-language-server#405]
Newer version of VSCode ships a new major of vscode-json-languageservice. To ease mixing both, it would be nice to have yaml-language-server able to work with this new major, otherwise multiple versions of vscode-json-languageservice need to be installed, leading to more disk space usage and more issues in some cases (eg https://github.com/eclipse/wildwebdeveloper/pull/618#issuecomment-777335910 )

**Comment by mickaelistria** [comment]
Thanks a lot @evidolob ! Do you have an estimation of what a new release of yaml-language-server is going to take place? Knowing that would help us in deciding when to produce next Wild Web Developer release.

**Comment by evidolob** [comment]
@mickaelistria Usually we make a release on sprint end. I add milestone to this issue.
