### ISSUE TITLE
Autocomplete not working when certain characters are in object property keys

### ISSUE THREAD

**Issue by jon-van** [redhat-developer/yaml-language-server#474]
## Describe the bug
If there is a colon in a property key name, it breaks the auto complete dropdown from working. For example, if i have the following schema:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "test description",
    "additionalProperties": false,
    "properties": {
        "Test: Colon": {
            "additionalProperties": false,
            "type": "object",
            "properties": {
                "none": {
                    "type": "boolean",
                    "enum": [
                        true
                    ]
                }
            }
        }
    }
}
```
when using vscode with the extension, the following happens:
![image](https://user-images.githubusercontent.com/7283171/116300280-b7fc3d80-a76c-11eb-9b0c-f78e5e5228ad.png)

However, if you add quotes around the object key in the YAML, the autocomplete dropdown works as expected as you can see in the following image:
![image](https://user-images.githubusercontent.com/7283171/116300404-dc581a00-a76c-11eb-85b1-1cb619516158.png)

I have also found the same issue arises when using other special characters at the start of the object key property name. This issue seems to be similar to the issue fixed here: https://github.com/redhat-developer/yaml-language-server/pull/435

Maybe if an object key starts with any non-alphanumeric/special characters, it should be quoted be default? And also if the object key contains a `:` it should also be quoted.

## Steps to Reproduce

1. Create a JSON schema using the schema from above
2. When using this schema with the vscode-yaml extension, use ctrl+space to have the dropdown auto complete option appear and select the item in the dropdown (in this example it is `Test: Colon`
3. See that when doing ctrl+space again under that object, it wont have the expected behavior where it has `none` as the selectable item in the dropdown.
4. If you then wrap the `Test: Colon` in quotes, and do ctrl+space again it will now have `none` as a selectable item in the typeahead.

## Environment
- [ ] Windows
- [x ] Mac
- [ ] Linux
- [ ] other (please specify)

I originally created this issue in the [vscode-yaml](https://github.com/redhat-developer/vscode-yaml/issues/496) repo, but after coming back to it, it seems like it should actually be here.

**Comment by JPinkney** [comment]
Should be fixed with https://github.com/redhat-developer/yaml-language-server/pull/475. The fix will be available in our next release

**Comment by jon-van** [comment]
Thanks @JPinkney!
