### ISSUE TITLE
Improve hover to include title, description and source schema link

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/yaml-language-server#480]
When hovering over an entry we can now see only the `title` from the schema and that may prove not enough for some schemas that also have a longer `description` field too.

Ideally it should look like:
```
{title}
{description}
Source: <a href='link-to-open-schema'>schema-filename.json</a>
```

I mention that both `title` and `description` may be missing and we should use whatever we find.

One example from XML schemas can be used as a nice implementation example

<img width="772" alt="Screenshot 2021-06-03 at 16 52 20" src="https://user-images.githubusercontent.com/102495/120666410-786bf400-c484-11eb-83d6-08065d6263ea.png">

Also the auto-complete field functionality does not display the field title after the name, something that is highly desired for ansible module arguments. Without this the user would be forced to first auto-complete the entry and make use of hover after in order to understand the purpose of that option.

![](https://sbarnea.com/ss/Screen-Shot-2021-06-03-16-39-36.80.png)

**Comment by evidolob** [comment]
@ssbarnea I create PR for hover.

As for completion, try to press `ctrl + space` twice you should see documentation popup:

<img width="1031" alt="Screenshot 2021-06-30 at 14 34 32" src="https://user-images.githubusercontent.com/929743/123953967-83953f80-d9b0-11eb-9da4-560f61da63be.png">

**Comment by ssbarnea** [comment]
@evidolob Can you please give me some hints on how to test that PR? I always wondered how am I supposed to test `yaml-language-server` as the deliverable is not an extension, so I need to include it in a local build vscode-yaml but that was not clear to me.

**Comment by evidolob** [comment]
Sure, there doc how to run vscode-yaml with own LS https://github.com/redhat-developer/vscode-yaml/blob/main/CONTRIBUTING.md#developing-the-client-and-server-together
