### ISSUE TITLE
How to use yaml formatter with Neovim builtin LSP client?

### ISSUE THREAD

**Issue by dhruvmanila** [redhat-developer/yaml-language-server#486]
The codebase contains a [yamlFormatter](https://github.com/redhat-developer/yaml-language-server/blob/main/src/languageservice/services/yamlFormatter.ts) although the [server capabilities says otherwise](https://github.com/redhat-developer/yaml-language-server/blob/main/src/yamlServerInit.ts#L99): 
```typescript
        documentFormattingProvider: false,
```

The formatter runs perfectly well in VSCode. I installed the server using `npm` and running the server with the default settings.

**Comment by dhruvmanila** [comment]
So, I did a bit of experimentation where I forced Neovim to send the formatting request by specifying that the server actually supports it using `client.resolved_capabilities.document_formatting = true` and the server responded appropriately.

My only question is why is the server specifying `documentFormattingProvider: false` while it actually can do the formatting?

**Comment by evidolob** [comment]
That true, we return `false` there https://github.com/redhat-developer/yaml-language-server/blob/main/src/yamlServerInit.ts#L99 for `documentFormattingProvider`.
@JPinkney Do you remember why?

**Comment by dhruvmanila** [comment]
I tracked it down to this PR (https://github.com/redhat-developer/yaml-language-server/pull/179) which fixes this issue (https://github.com/redhat-developer/vscode-yaml/issues/220) although I'm not sure I understand the reasoning behind this.

**Comment by JPinkney** [comment]
IIRC it was done that way because VSCode needed formatters to be registered dynamically so that you could dispose of them after they weren't in use. I'm not sure if that's still neccessary though. You might be able to set `documentFormattingProvider` to true now

**Comment by dhruvmanila** [comment]
There's already an open PR for this: https://github.com/redhat-developer/yaml-language-server/pull/316 although it's outdated and needs rebasing.

**Comment by dhruvmanila** [comment]
For reference, the `vscode-json-languageserver` provides the initialization option `provideFormatter` which will then determine whether to provide the formatter on initialization or not.

Source: https://github.com/microsoft/vscode/blob/41c86e5bb8c29f801d6036b738c0c6b548be58e5/extensions/json-language-features/server/src/jsonServer.ts#L140-L141

From the [README (server#initialization-options)](https://github.com/microsoft/vscode/tree/main/extensions/json-language-features/server#initialization-options):
> `provideFormatter: boolean | undefined`. If defined, the value defines whether the server provides the `documentRangeFormattingProvider` capability on initialization. If undefined, the setting `json.format.enable` is used to determine whether formatting is provided. The formatter will then be registered through dynamic registration. If the client does not support dynamic registration, no formatter will be available.

**Comment by ttys3** [comment]
I encountered the same problem

**Comment by lewissetter** [comment]
Why was #316 closed? I think #657 is the same problem we're talking about here. From what @dhruvmanila [mentioned](https://github.com/redhat-developer/yaml-language-server/issues/486#issuecomment-861722056), it looks like `documentFormattingProvider` can be set to true since leaving `provideFormatter` undefined will the formatter to be registered dynamically.

**Comment by meatballs** [comment]
> So, I did a bit of experimentation where I forced Neovim to send the formatting request by specifying that the server actually supports it using `client.resolved_capabilities.document_formatting = true` and the server responded appropriately.

Would you mind sharing how you did that?

**Comment by meatballs** [comment]
Never mind. I got it working myself by adding a line to my `on_attach` function:

```
local on_attach = function(client, bufnr)
  client.resolved_capabilities.document_formatting = true
```

**Comment by dhruvmanila** [comment]
I think you should directly use `prettier` for YAML files as the language server uses that internally.

https://github.com/redhat-developer/yaml-language-server/blob/f03324a3a81c1a32b153b61dea685308865b5dac/src/languageservice/services/yamlFormatter.ts#L47

But, if you want to use the language server, then I suggest to guard the line so that it only affects the YAML language server:
```lua
local on_attach = function(client, buffer)
  if client.name == "yamlls" then
    client.resolved_capabilities.document_formatting = true
  end
end
```

**Comment by seanturner026** [comment]
> I think you should directly use prettier for YAML files as the language server uses that internally.

How would one implement this with neovim?

**Comment by dhruvmanila** [comment]
> How would one implement this with neovim?

Using a formatter plugin like https://github.com/stevearc/conform.nvim. You can find a list here: https://github.com/rockerBOO/awesome-neovim#formatting

**Comment by seanturner026** [comment]
Awesome! I was able to get it working super easily (the method above in this PR wasn't working).

https://github.com/seanturner026/kickstart.nvim/commit/507223e9ac67d8bec513b1d551103004b8d1bb38
