### ISSUE TITLE
NPM Publishing

### ISSUE THREAD

**Issue by liuderchi** [redhat-developer/yaml-language-server#5]
Thanks for your awesome YAML language server implementation 💯 
I would like to develop yaml-plugin for another editor.

> Are you planning to *publish the ./server/\* on NPM*?

**Comment by JPinkney** [comment]
We have now made this available on npm! https://www.npmjs.com/package/yaml-language-server. We also included your extension in our readme!

**Comment by liuderchi** [comment]
@JPinkney Huge thanks.

Currently I'm importing *yaml-lang-server* by using [napa][napa]
plus declaring [repo dependency][repo-dep] and [compile script][compile-script],
which are workarounds for repo without package.json.

Now your npm release is a great help. 🎉 

[napa]: https://www.npmjs.com/package/napa "napa"
[repo-dep]: https://github.com/liuderchi/ide-yaml/blob/master/package.json#L37 "repo-dep"
[compile-script]: https://github.com/liuderchi/ide-yaml/blob/master/package.json#L8 "compile-script"

**Comment by liuderchi** [comment]
BTW perhaps you would like to add [npm version badge](https://shields.io/#version) to README?

[![version](https://img.shields.io/npm/v/yaml-language-server.svg)](https://www.npmjs.com/package/yaml-language-server)

copy this markdown:
```markdown
[![version](https://img.shields.io/npm/v/yaml-language-server.svg)](https://www.npmjs.com/package/yaml-language-server)
```

**Comment by liuderchi** [comment]
@JPinkney thanks for the npm release and it's really helpful 💯 

When I was browsing the [yaml-language-server npm page](https://www.npmjs.com/package/yaml-language-server), I found that there is no github url linking to this repo.

**Comment by JPinkney** [comment]
Thanks!

I’ll get that added for the next release of it (should be soon)!


On Oct 12, 2017, at 12:08 AM, Te-Chi Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


@JPinkney<https://github.com/jpinkney> thanks for the npm release and it's really helpful 💯

When I was browsing the yaml-language-server npm page<https://www.npmjs.com/package/yaml-language-server>, I found that there is no github url linking to this repo.
