### ISSUE TITLE
Autocompletion fails on value item mid typing only on first line (Only kubernetes schema)

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#51]
When you're typing something like
```
kind: Ima
```
with kubernetes schema it fails to autocomplete only on the first line

**Comment by andxu** [comment]
Once user has selected/configured the yaml file as kubernetes manifest file, I am able to provide the in-memory schema  composed by all possible kinds, the pain point is how to think it is a kubernetes yaml during middle of the editing phase.

**Comment by JPinkney** [comment]
This issue shouldn't affect that, this one is only for general auto completion on the first line.

> how to think it is a kubernetes yaml during middle of the editing phase since the detection I used is by kind

I'm not sure how you could do it by just kind unless there are no two kinds that are the same across all the yaml files you're trying to match too. Or if you tried to get other values that a user has written in the file as well.

**Comment by JPinkney** [comment]
As an interesting consequence of my work on openshift console I've found out this is actually a kubernetes schema bug. When I manually convert the OpenAPI to JSON schema inside of openshift console I actually don't have this issue.
