### ISSUE TITLE
Loading JSON schema is broken when using a hash in a schema URL

### ISSUE THREAD

**Issue by remcohaszing** [redhat-developer/yaml-language-server#514]
## Describe the bug
I created a modeline referencing a JSON schema based on a json pointer as part of a hash.

```yaml
# yaml-language-server: $schema=https://appsemble.app/api.json#/components/schemas/AppDefinition
```

This no longer works as of version `0.21.0`.

## Expected Behavior

Schema completion and validation work, as it did in version `0.20.0`

## Current Behavior
`vscode-yaml@0.20.0`: Schema completion and validation work as expected.

![image](https://user-images.githubusercontent.com/779047/126147222-4d6e0b19-ccde-41dc-813a-e4d8838949fc.png)

`vscode-yaml@0.20.1`: VSCode reports the problem: `Unable to load schema from '/home/remco/Projects/appsemble/apps/person/https:/appsemble.app/api.json#/components/schemas/AppDefinition'`.

![image](https://user-images.githubusercontent.com/779047/126147128-24187dd1-4c41-47a6-8a2e-5a0dda3ca67c.png)

`vscode-yaml@0.21.0`: Schema validation fails silently.

![image](https://user-images.githubusercontent.com/779047/126147044-1b194927-b95b-47c4-803b-120040dba40a.png)

## Steps to Reproduce

1. Create a YAML file.
2. Add the modeline:
   ```yaml
   # yaml-language-server: $schema=https://appsemble.app/api.json#/components/schemas/AppDefinition
   ```
3. In VSCode, alternate between the different extension versions, which can be done by clicking the dropdown icon on the `Uninstall` button on the extension page.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

**Comment by evidolob** [comment]
Duplicate of https://github.com/redhat-developer/vscode-yaml/issues/557 
Should be fixed with https://github.com/redhat-developer/yaml-language-server/pull/512

**Comment by remcohaszing** [comment]
Yep, definitely a duplicate. Sorry! :sweat_smile:
