### ISSUE TITLE
Some source files are missing license headers

### ISSUE THREAD

**Issue by rcjsuen** [redhat-developer/yaml-language-server#52]
The following files are missing license headers:
- [src/languageservice/yamlLanguageService.ts](https://github.com/redhat-developer/yaml-language-server/blob/9cbe196d57a22adb91828ffee5903c63119f6aa4/src/languageservice/yamlLanguageService.ts)
- [src/languageservice/parser/yamlParser.ts](https://github.com/redhat-developer/yaml-language-server/blob/9cbe196d57a22adb91828ffee5903c63119f6aa4/src/languageservice/parser/yamlParser.ts)
- [src/languageservice/utils/arrUtils.ts](https://github.com/redhat-developer/yaml-language-server/blob/9cbe196d57a22adb91828ffee5903c63119f6aa4/src/languageservice/utils/arrUtils.ts)
- [src/languageservice/utils/documentPositionCalculator.ts](https://github.com/redhat-developer/yaml-language-server/blob/9cbe196d57a22adb91828ffee5903c63119f6aa4/src/languageservice/utils/documentPositionCalculator.ts)

**Comment by JPinkney** [comment]
Added and updated license headers: https://github.com/redhat-developer/yaml-language-server/commit/f11414744377f161404d4fa173a13091614d3ee8
