### ISSUE TITLE
Why is npm not supported?

### ISSUE THREAD

**Issue by sul4bh** [redhat-developer/yaml-language-server#521]
## Summary
Why is npm not supported?

## Relevant information
I see that this repo does not support npm in favor of yarn: https://github.com/redhat-developer/yaml-language-server/blob/0.22.0/package.json#L22

I am curious to know why that is the case? What kind of issues did you run into with npm? Do you want to support npm in the future?

I am asking because npm is the default package manager for node and supporting it would make life easier for a lot of users.

**Comment by remcohaszing** [comment]
When installing this using npm, it shows an annoying warning that’s unnecessary.

```sh
$ npm i yaml-language-server@0.22.0
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml-language-server@0.22.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '*',
npm WARN EBADENGINE     npm: '\n\nERROR: Please use yarn, npm is not supported in this repository!!!\n\n',
npm WARN EBADENGINE     yarn: '^1.22.5'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.21.0' }
npm WARN EBADENGINE }
```

I understand this repository uses yarn, but there’s no reason for this project to advocate yarn (or even a specific yarn version) over npm for its users.

**Comment by gorkem** [comment]
Ahh I see the `required` statement. Agreed. I do not think there is that hard dependency to `yarn` anymore. Do you want to do the honours and send a PR?
