### ISSUE TITLE
Is it possible to support Helm.sh templating in option please?

### ISSUE THREAD

**Issue by lakano** [redhat-developer/yaml-language-server#53]
Hi !
Helm is now the official package manager of Kubernetes. K8s configuration is a lot based under yaml files, and Helm have a templating system to help to replace values in the yaml configuration, but also to control the flow ( {{ if ... }} {{ end }} ).
Of course, it's not YAML compatible ( at least fo the flow control https://docs.helm.sh/chart_template_guide/#flow-control ).
May be it's possible to bypass the errors/warning, based on the extension (eg: file.helm) ?
Regards,

**Comment by andxu** [comment]
in fact, the helm yaml is not a yaml compatible to yaml parser, I will do the parse work(helm languange server) which will be used in vscode kubernetes  tools.

**Comment by andxu** [comment]
@JPinkney yaml-language-server has not been published for over 2 months, when is the planed release date for the next publish(see https://www.npmjs.com/package/yaml-language-server)?

**Comment by JPinkney** [comment]
@andxu Next release will hopefully be in 10 days. We just need to close a few issues first.

**Comment by JPinkney** [comment]
Going to close this issue because helm yaml is not compatible to yaml parser.
