### ISSUE TITLE
Apply schema to custom file name

### ISSUE THREAD

**Issue by mawkler** [redhat-developer/yaml-language-server#543]
I would like to apply the OpenAPI (swagger) schema to a YAML file that's not named `openapi.yaml`. The schema seems to only apply to files named `openapi.yaml`. How can I tell yaml-language-server to apply [the openapi schema](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json) to a file with a custom file name?

Also, would this configuration be possible to set in a project's `package.json` file?

**Comment by evidolob** [comment]
@Melkster You can use [settings](https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas) to map your schema to file.

**Comment by Melkster** [comment]
I've tried adding this to my config but it doesn't seem to apply the schema:

```json
"yaml": {
  "schemas": {
    "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json":  "custom-filename.yaml"
  }
}
```

**Comment by evidolob** [comment]
hm, that strange. Could you try:
```json
"yaml.schemas": {
    "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json":  "custom-filename.yaml"
}
```

**Comment by Melkster** [comment]
Nope, still doesn't work :/

The thing is that I'm using yaml-language-server with [Neovim's built-in LSP client](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#yamlls), which is configured using Lua, not JSON, and I've tried various configurations, including

```lua
{
  ['yaml.schemas'] = {
    ['https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json'] = 'custom-filename.yaml'
  },
}
```

and

```lua
{
  ['yaml'] = {
    ['schemas'] = {
      ['https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json'] = 'custom-filename.yaml'
    }
  },
}
```

**Comment by apupier** [comment]
You can try to use an inlined declaration of the yaml schema, see https://github.com/redhat-developer/yaml-language-server#using-inlined-schema

so would be something like:
`# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json`

![Screenshot from 2021-10-21 11-20-16](https://user-images.githubusercontent.com/1105127/138249096-a9a7048e-1fa7-45ad-82af-58373eda4e2d.png)

**Comment by gorkem** [comment]
@mawkler have you got this working eventually? This is a feature that works on vscode. I am closing this, for now, let us know if this still needs our attention.
