### ISSUE TITLE
Can´t ignore, disable or change schema for certain files - kustomization yaml patches in this case

### ISSUE THREAD

**Issue by rille111** [redhat-developer/yaml-language-server#570]
## Describe the bug

Can´t ignore / disable or change the schema for validation on certain files. In this case it´s a kustomization patch file. It wants to validate to the kubernetes schema, therefore complains that the .yaml patch file doesn´t match the expectations.

### Example
**patch.yaml**
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
```

### Possible solution
I could see a solution that configuring settings.json would ignore or at least change the validation schema following a glob pattern. Example:
``` json
{
    "yaml.schemas": {
        "https://json.schemastore.org/yamllint.json": "**/patch.yaml",
     }
}
```
Or
``` json
{
    "yaml.schemas": {
        "ignore": "**/patch.yaml",
     }
}
```

## Expected Behavior
Different schema to validate against, or disable altogether.

## Current Behavior
Everything gets validated according to kubernetes if it sees kubernetes stuff inside the yamls.

## Steps to Reproduce

1. Create a patch.yaml
2. Use the previously attached code
3. Observe the problems in VSCode

## Environment
- [x ] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by gorkem** [comment]
Closing as this is on the purview of vscode-kubernetes-tools
