### ISSUE TITLE
Autocomplete should not escape colon without white-space following

### ISSUE THREAD

**Issue by donorp** [redhat-developer/yaml-language-server#571]
### Is your enhancement related to a problem? Please describe.

Introduced in #475 as the fix of #474 : property name with colon gets escaped.

But when the key is in `part-a:part-b` or `:part-b` format, there is no white-sapce following the colon, the colon is not indicating a map, we should not escape the key, as that's just plain yaml string.

### Describe the solution you would like

Do not escape keys in `part-a:part-b` or `:part-b` format.

### Describe alternatives you have considered

None.

### Additional context

Further more, yaml accepts arbitrary map key, the key can be a map or an array:

```yaml
{k1: v1, k2: v2}: v3
[v1, v2]: v3
```

probably that should not be considered for now.

**Comment by evidolob** [comment]
Resolved with https://github.com/redhat-developer/yaml-language-server/pull/572
