### ISSUE TITLE
LSP triggering`registerCapability` despite `dynamicRegistration` set to false

### ISSUE THREAD

**Issue by WhyNotHugo** [redhat-developer/yaml-language-server#583]
## Describe the bug

When using `yaml-language-server` I see this printed on my logs:

The language server yamlls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream.

The LSP exits soon after -- I've no idea if both issues are related, but this issue still does make sense.

## Expected Behavior

Should not triggers a registerCapability if dynamicRegistration set to false.

## Current Behavior

Triggers a registerCapability if dynamicRegistration set to false.

## Steps to Reproduce

No special steps merely configured nvim (using nvim-lspconfig) and opened a YAML file.

## Environment
- Linux

**Comment by msivasubramaniaan** [comment]
@WhyNotHugo can you please share the **.vim** config file which you used. It would help us to reproduce the issue at the earliest.
