### ISSUE TITLE
Support for custom yaml tags (e.g. "!include")

### ISSUE THREAD

**Issue by akaRem** [redhat-developer/yaml-language-server#59]
Hi! 

There is an issue in YAML plugin for VS Code https://github.com/redhat-developer/vscode-yaml/issues/76
In short: custom YAML tags such as `!include`, `!vault` (and many others) that are used in Ansible, CloudFomation, JenkinsJobBuilder and many other utilities are not supported. But these tags are Language feature (see more details in attached link)

As far as I understand, the problem is somewhere in lang. server. because it's used as backend for mentioned plugin.

Could you please investigate possibilities to implement this in language server, so folks from vscode-yaml will be able to support this in plugin?

**Comment by JPinkney** [comment]
It is because the parser currently does not support custom yaml tags. I'm looking into a parser that supports both custom yaml tags and comments right now for this issue and https://github.com/redhat-developer/vscode-yaml/issues/75.

**Comment by kace91** [comment]
@JPinkney  Hi!

Have you been able to find any parser that can potentially add those features and replace the current one? 

My company is right now developing a yaml-based language for some private needs, and we'd need support for !include tags as well as possibly comments. We're considering using this server and contributing to it, so we'd appreciate it if you can share what you've managed to investigate so far :)

**Comment by JPinkney** [comment]
Added in 0.0.12 release!
