### ISSUE TITLE
Path fix of npm run watch

### ISSUE THREAD

**Issue by liuderchi** [redhat-developer/yaml-language-server#6]
it seems that watch section of package.json script has path issues

https://github.com/redhat-developer/yaml-language-server/blob/655b8699247d5e4e48d94ca8c14e6c22350d7311/package.json#L43

`../out` is not existed in the repo currently

related commit is [668c1204](https://github.com/redhat-developer/yaml-language-server/blob/668c120488f3b667930c5209515af4d94bf58cb5/package.json)

**Comment by JPinkney** [comment]
Fixed in 10299103ac753bbbb36404a8844864c2c920ae38
