### ISSUE TITLE
Support versions from schemastore

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/yaml-language-server#639]
Schemastore has a `versions` field that lists the older versions of a schema. As you can see from the example below the `url` field points to the latest/default schema while `versions` lists all versions available. We should introduce a code lens to switch between the versions of a schema. 

Moreover, we can use values of fields such as `apiVersion` or `schemaVersion` to match the schema version. 

```JSON  
     "name": "Airlock Microgateway",
     "description": "Airlock Microgateway configuration schema",
      "url": "https://json.schemastore.org/airlock-microgateway-3.1.json",
      "fileMatch": [
        "microgateway-config.yaml",
        "microgateway-config.yml",
        "airlock-microgateway-config.yaml",
        "airlock-microgateway-config.yml"
      ],
      "versions": {
        "3.0": "https://json.schemastore.org/airlock-microgateway-3.0.json",
        "3.1": "https://json.schemastore.org/airlock-microgateway-3.1.json"
      }
```

**Comment by maysunfaisal** [comment]
What happens if a schema does not have properties like `apiVersion` or `schemaVersion` and still has support for multiple versions in the schema store?

**Comment by evidolob** [comment]
I was thinking on providing some some of UI, to allow select schema with specific version

**Comment by gorkem** [comment]
A schema with 2 versions as separate entries in the schema store is a bug on schema that should be fixed on the schema store. The `versions` API suggests that the schema store intends to solve multiple versions with this API.

**Comment by gorkem** [comment]
What do you have in mind for UI?

**Comment by evidolob** [comment]
We don't have a much options, I was thinking on extending status bar item which currently show current schema, I may extend it functionality, and add schema version selection(in case if used schema from json schema store and has more then one version) 
Other option is adding more codelens items on schema, like `Schema.json(2.1) | Use 1.0 | Use 2.0`, click on `Use {version}` will change current schema.

**Comment by gorkem** [comment]
I favor the status bar option too. Code lens is too invasive for this kind of usage

**Comment by evidolob** [comment]
@gorkem There demo for what I have now:

https://user-images.githubusercontent.com/929743/155338421-df05ad28-22ee-4416-bfc3-29bca724693e.mov

Is it obvious way to change used json schema version?

**Comment by evidolob** [comment]
@gorkem Could you look on my demo?

**Comment by gorkem** [comment]
Yes, the UI looks OK. How are we going to remember the selected version? Is it going to be a selection per file/workspace?

**Comment by evidolob** [comment]
I plan to store it in user preferences, workspace first

**Comment by gorkem** [comment]
Yes, preferences make sense.
