### ISSUE TITLE
project-specific config

### ISSUE THREAD

**Issue by jasonkuhrt** [redhat-developer/yaml-language-server#68]
For example I have a project using [`!Sub`](http://www.fischco.org/technica/2017/cloud-formation-sub/) (For AWS CloudFormation) but this is not something that all projects share.

From what I can tell, in `vscode`, the settings are global.

A solution might be to read from a config file local to the project e.g. `.ide-yaml.config` (or whatever better standard).

**Comment by JPinkney** [comment]
I believe in VSCode there is a notion of workspace settings. That is already a config file local to the project (stored in .vscode/settings.json I believe)

**Comment by jasonkuhrt** [comment]
Ah true. Wonder if same is true of other editors. I can see how this is arguably not a concern of YLS...

**Comment by JPinkney** [comment]
I think I am going to close this and leave it up to the editor to provide project specific configs
