### ISSUE TITLE
Subschema mappings wrongly assign the parent schema file

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/yaml-language-server#694]
## Describe the bug

When using subschemas, this extension will end-up trying to validate the documents using both the subschema and the main schema bundle file, which obviously will not pass.

By subschema, I mean using the documented in-document bookmarking for referring to a specific definition from within a schema file.

For example `https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json#/definitions/playbook` should load `ansible.json` schema file and use the `playbook` definition from it.

AFAIK, all validators are able to process schemas like this and apparently even vscode-yaml, to some extend.

For example we tested with both `ajv` and the validator used by Microsoft in vscode and both work as expected.

## Expected Behavior

Configuring a subschema should not have undesired side effects like attempt to use the main schema file for validation.

In our example that schema file does only have definitions in it, which is still perfectly fine for a schema file that is never expected to be used without a subschema selector. Still, extension does seems to not like the `No content.` aspect of it.

## Current Behavior

This shows that the subschema is loaded correctly because the header line display the subschema name and not the title of the whole bundle.
![](https://sbarnea.com/ss/Screen-Shot-2022-04-04-15-11-38.95.png)

Still, at the same time a problem is identified:
```
Problems loading reference 'schemaservice://combinedschema/f/ansible.json#/definitions/tasks': Unable to load schema from 'schemaservice://combinedschema/f/ansible.json': No content.
```
![](https://sbarnea.com/ss/Screen-Shot-2022-04-04-15-13-14.15.png)

## Steps to Reproduce
1. Configure a subschmema mapping like `"https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json#/definitions/playbook": ['playbook.yml']`
2. Open 'playbook.yml' and observe the attempt to use two schemas, one correct one and one incorrect, the one without a "#" url.

So far I was not able to find a workaround yet.

**Comment by ssbarnea** [comment]
This might also be caused by #453 but in our case the problem is more serious, as we never configured relative paths for schemas, and we have no workaround to make it work.

The code throwing this error fro https://github.com/redhat-developer/yaml-language-server/blob/360c0380b7a59c6722f91e8165af20bd2b8a99d4/src/languageservice/services/yamlSchemaService.ts#L623-L631 also looks buggy because it fails to display the errors that caused the load failure, even if they are clearly not empty.

**Comment by ssbarnea** [comment]
Based of further testing I am now starting to believe that this bug might appear only on projects that use relative paths, like our schemas project itself. 

See https://github.com/ansible/schemas/blob/main/.vscode/settings.json#L18-L22

As ability to test the schema changes directly into the editor is essential during development, we need to find a solution for this problem. Any ideas?

**Comment by ssbarnea** [comment]
Closing it because I am unable to reproduce it today but I suspect it was caused by use or relative paths.

**Comment by metal3d** [comment]
@ssbarnea you can see https://github.com/neoclide/coc-yaml/issues/64 to reproduce
