### ISSUE TITLE
it is only for .yml?

### ISSUE THREAD

**Issue by JosonJiang** [redhat-developer/yaml-language-server#699]
I have a  file named  xxx.yaml ;it is  not work 

![1](https://user-images.githubusercontent.com/3362073/163184115-fcc119da-4750-45e6-802a-69865a1d729f.png)

![2](https://user-images.githubusercontent.com/3362073/163184137-738279d3-6ac7-49cb-8822-055d08fc60a6.png)

![9](https://user-images.githubusercontent.com/3362073/163184165-5227d494-d615-4a5e-9806-c89c52bdae60.png)

![3](https://user-images.githubusercontent.com/3362073/163184463-d4a7588d-89d9-4a26-8b94-8135077e84c7.png)

How can i use it;  if i have a file name with xxx.yaml

## Environment
- [ √] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by gorkem** [comment]
Is this with VScode? I am testing it, and I can not replicate it. The only option that comes to my mind is another extension on your environment interfering with the `.yaml` filename extension. What is the language  mode that you see with .yaml?

**Comment by gorkem** [comment]
I remembered this was also reported for https://github.com/redhat-developer/vscode-yaml/issues/746. Closing in favour of vscode-yaml report
