### ISSUE TITLE
Support markdown frontmatter

### ISSUE THREAD

**Issue by remcohaszing** [redhat-developer/yaml-language-server#710]
### Is your enhancement related to a problem? Please describe.

Some projects require markdown frontmatter data to follow a specific schema. Typically frontmatter data uses the following syntax:

```markdown
---
title: frontmatter using triple dashes is typically interpreted as YAML
---

Anything below is treated as markdown
```

Most implementations only allow a single frontmatter section and only if it’s on top.

### Describe the solution you would like

It would be nice `yaml-language-server` could also validate frontmatter for markdown and MDX documents.

### Describe alternatives you have considered

N/A

### Additional context

It’s just an idea. I understand if this is out of scope.

**Comment by gorkem** [comment]
In this case, [yaml is embedded](https://code.visualstudio.com/api/language-extensions/embedded-languages) to markdown. It is best that the language server/service handling the markdown should forward the requests to yaml-language-server. I am not sure if we need to implement any LSP features that we do not already have.

**Comment by remcohaszing** [comment]
Yep, makes sense! I don’t think anything needs to happen in `yaml-language-server` for this.
