### ISSUE TITLE
Is there a way to set/unset a schema?

### ISSUE THREAD

**Issue by mosheavni** [redhat-developer/yaml-language-server#713]
## Summary
I'm trying to better integrate nvim-lsp client with this language server.
Is there a request I can send a server request to set which schema I want to use without manipulating the settings passed to the server?

There is a great way of getting all schemas (`yaml/get/all/jsonSchemas`) or what schemas are active now ('yaml/get/jsonSchema`), are there any requests to set or unset the schema?

Thanks.

**Comment by someone-stole-my-name** [comment]
See https://github.com/someone-stole-my-name/yaml-companion.nvim

**Comment by mosheavni** [comment]
> See https://github.com/someone-stole-my-name/yaml-companion.nvim

Really cool!
I actually wrote it myself over the weekend, with a very similar approach:
https://github.com/mosheavni/dotfiles/blob/f62c33f8735b789dde035afefb38a02754b2db97/.config/nvim/lua/user/select-schema.lua
