### ISSUE TITLE
Duplicated IntelliSense with YAML + Docker extension 

### ISSUE THREAD

**Issue by ucheNkadiCode** [redhat-developer/yaml-language-server#715]
As our team has added the Docker Compose Language service to yaml files that are given the Docker Compose language designation in VS Code, users are getting dual suggestions in IntelliSense if they have the Docker extension installed.

Original Issue: https://github.com/microsoft/vscode-docker/issues/3480

Our suggestion would be, could there be a setting or an experience to suppress these suggestions if 

Options: 
1. Docker extension is detected and the user gives a Docker Compose file designation in VS Code
2. User has a file named `docker-compose.yml`

I like the first option. Althrough the majority of users name their Docker Compose file `docker-compose.yml`, this provides the greatest flexibility. 

Adding @bwateratmsft

**Comment by gorkem** [comment]
I think removing[ this line ](https://github.com/redhat-developer/vscode-yaml/blob/a9689529c28cfe83c87e0734e3aa0a84994e76fd/package.json#L43)should do the trick.

**Comment by bwateratmsft** [comment]
It would partway fix it, but if YAML got activated anyway for another reason, this would still occur. I talked to @isidorn and there's not an existing way in VSCode to choose one language server or another. I think the "best" solution would be a shared setting between Docker and YAML; an _easier_ solution would be a setting in YAML to turn off for `dockercompose` language entirely (including the language client document selector), but would require the user to manage two separate settings.

I don't think it's particularly urgent; as a workaround the Docker extension has a setting to disable its language server for compose, leaving only the YAML one.

**Comment by ucheNkadiCode** [comment]
@bwateratmsft, could we start off with the partway fix? 

@bwateratmsft  and @gorkem, how would we go about creating a shared setting that each of our extensions react to? Hopefully this wouldn't be too much work. Ultimately it makes either of our extensions look "broken" when the user is in any file with a Docker compose language designation.

**Comment by bwateratmsft** [comment]
I've got much higher priority work at the moment so it could be a bit, but first I would need to do some testing/investigating to iron out a couple of things.

- Anything bad happen if two extensions contribute the same setting ID?
    - Corollary: can multiple extensions each contribute an enum value to a shared setting?
- What's the behavior if two extensions contribute conflicting configuration defaults? e.g. does one of them "win" randomly, or is it the first installed wins, or the last installed...etc. @isidorn might know the answer to this.
- If one of the extensions is uninstalled but was the chosen language service for compose files, what happens?
- Do we need a custom experience for helping the user choose, or is the settings UI alone enough? The answer maybe depends on all of the above.

After that we'd just need to agree on exact setting IDs and values, and get their use implemented in source.

**Comment by gorkem** [comment]
Have you considered removing the YAML language functionality from the docker extension? What is the functionality missing on `vscode-yaml`?

**Comment by isidorn** [comment]
@bwateratmsft the last one that gets activated should win. If they activate on the same event then it is a game of chance I guess...

**Comment by bwateratmsft** [comment]
Well, upon testing, I found that two extensions _cannot_ contribute the same setting (they can both do setting default values, but not the settings themselves), so that plan is out.

**Comment by ucheNkadiCode** [comment]
> Have you considered removing the YAML language functionality from the docker extension? What is the functionality missing on `vscode-yaml`?

Our Docker Compose Language Service has quite a few features that handle complex scenarios for folks using a file designated at as a Docker Compose YAML file. Options like scaffolding, various snippets like tab completions for ports, volumes, build are features we've added from direct customer feedback. We feel like in this situation, we've built the Docker Compose language service to add more functionality in the case of a Compose file than vscode-yaml

**Comment by fbricon** [comment]
Other vscode extensions, like [Kubernetes](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools) simply contribute new functionalities (validation/completion) to the yaml language server by injecting a custom schema, that can be computed on-the-fly. See https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/92582a57ce722e166d25482b443c37a58d16305a/src/yaml-support/yaml-schema.ts.

**Comment by Igorgro** [comment]
From user perspective this https://github.com/redhat-developer/yaml-language-server/issues/715#issuecomment-1130350015 solves a problem at least until the extension update

**Comment by bwateratmsft** [comment]
@gorkem You can close this issue. We did some deconfliction work so that the Docker extension yields to YAML's features when it is present, while still maintaining some of its unique features. https://github.com/microsoft/compose-language-service/issues/122

The Docker Compose schema document is still...not great but that's orthogonal to all this.

**Comment by gorkem** [comment]
@bwateratmsft Thanks for letting us know.
