### ISSUE TITLE
The validator should support null values

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/yaml-language-server#72]
Current yaml validator will report an error for `null` value when the schema type is `string`.
![image](https://user-images.githubusercontent.com/14052197/40948544-93847250-689b-11e8-8519-354a13777071.png)

Actually, `null` is a valid `string` type. Similarly, `array`/`object` type should support `null`, too.

**Comment by JPinkney** [comment]
Fixed as of 6830f570588a4cbeb8128415633247214b793722. Will be included in the release Monday.

**Comment by testforstephen** [comment]
Awesome, thanks for the quick fix.
