### ISSUE TITLE
Use textDocument.formatting.dynamicRegistration?

### ISSUE THREAD

**Issue by iquiw** [redhat-developer/yaml-language-server#74]
yaml-language-server currently uses `workspace.symbol.dynamicRegistration` to determine whether it registers `textDocument/formatting` capability.

According to [the language-server-protocol spec](https://microsoft.github.io/language-server-protocol/specification#initialize), `textDocument.formatting.dynamicRegistration` looks appropriate for the purpose.

```
/**
 * Text document specific client capabilities.
 */
export interface TextDocumentClientCapabilities {
...
	/**
	 * Capabilities specific to the `textDocument/formatting`
	 */
	formatting?: {
		/**
		 * Whether formatting supports dynamic registration.
		 */
		dynamicRegistration?: boolean;
	};
```

**Comment by JPinkney** [comment]
Yes that should be changed. Is that something you'd like to contribute?

**Comment by iquiw** [comment]
I sent PR. As far as checked, formatting works as previous on VSCode.

**Comment by JPinkney** [comment]
Awesome thanks! I'll merge it!
