### ISSUE TITLE
Can we use Yaml-language-server-in CLI

### ISSUE THREAD

**Issue by ChetanKB** [redhat-developer/yaml-language-server#741]
Hi all,
### I have a YAML file and JSON schema file, I need to validate the YAML file against that JSON schema, I also want to compare the YAML file and check the YAML Validation. How can I use the yaml-language-server in the command-line interface?
** If this is not possible please could you suggest any other tool with that I can do the YAML validation and comparison with JSON schema.**

**Comment by rene-descartes2021** [comment]
Search the open issues before opening a new one.

Duplicate with #535.

**Comment by gorkem** [comment]
closing in favour of referenced issue
