### ISSUE TITLE
Is there any way to validate the yaml against the json schema using CLI?

### ISSUE THREAD

**Issue by chakra-123** [redhat-developer/yaml-language-server#756]
## Summary
Hi @JPinkney  @joshuawilson,
Does this tool have an option to validate a YAML file against a JSON schema using the command line?
## Relevant information
I need to validate my YAML files against the JSON schemas present in the JSON schema store in the CI pipeline.

**Comment by rene-descartes2021** [comment]
Search the open issues before opening a new one.

Duplicate with #535.

**Comment by gorkem** [comment]
Closing in favor of referenced issues
