### ISSUE TITLE
Execute command jumpToSchema already exists

### ISSUE THREAD

**Issue by VimalKumarS** [redhat-developer/yaml-language-server#765]
## Relevant information
Hello,
I am developing extension using 'yaml-langauge-server',   When i start server, it throws error "jumpToSchema already exists".
I also have redhat-yaml extension installed, on uninstalling redhat-yaml extension, yaml node server works.
Question 
Is there a way for extension if reusing component/library underneath can skip the command registered, or to check if yaml language server already running ?

thanks

**Comment by gorkem** [comment]
Are you embedding the `yaml-language-server` to another vscode extension? If that is the case,  we do not really support such a use.  We encourage other extensions to depend on the `vscode-yaml` from your extension.  Let me know if this will work for your case.

**Comment by gorkem** [comment]
Closing as embedding is not really supported
