### ISSUE TITLE
[Regression] Cloudformation Support

### ISSUE THREAD

**Issue by 17twenty** [redhat-developer/yaml-language-server#77]
Originally closed issue in https://github.com/redhat-developer/yaml-language-server/issues/20 but it looks like Cloudformation support is no longer present.

![image](https://user-images.githubusercontent.com/379176/42928920-f4cc788e-8b7b-11e8-8151-21ed11ac9073.png)

This is with the following tags:
```
...
    "yaml.customTags": [
        "!Ref",
        "!GetAtt",
        "!FindInMap sequence",
        "!FindInMap scalar",
        "!GetAtt",
        "!GetAZs",
        "!Cidr",
        "!ImportValue",
        "!Join sequence",
        "!Select",
        "!Split",
        "!Sub sequence",
        "!Sub scalar",
        "!And",
        "!Equals",
        "!If",
        "!Not",
        "!Or"
    ]
```

**Comment by 17twenty** [comment]
```
unacceptable node kind for !<!FindInMap> tag; it should be "scalar", not "sequence"
```

**Comment by 17twenty** [comment]
It also triggers follow on errors like `missed comma between flow collection entries` but that seems to be a knock on effect of the previous

**Comment by JPinkney** [comment]
It looks like instead of checking if the !FindInMap contains either scalar or sequence its looking like it is instead throwing an error when one one is found but not the other.

**Comment by 17twenty** [comment]
The sample above is from the AWS codepipeline tutorial here https://s3.amazonaws.com/cloudformation-examples/user-guide/continuous-deployment/wordpress-single-instance.zip

Hope that helps!

**Comment by dessite** [comment]
Any luck with fixing?
I have error

`unknown tag <!Ref>`

despite having

```
"yaml.customTags": [
        "!Ref",
        "!GetAtt",
        "!FindInMap sequence",
        "!FindInMap scalar",
        "!GetAtt",
        "!GetAZs",
        "!Cidr",
        "!ImportValue",
        "!Join sequence",
        "!Select",
        "!Split",
        "!Sub sequence",
        "!Sub scalar",
        "!And",
        "!Equals",
        "!If",
        "!Not",
        "!Or"
    ]
```

**Comment by str3tch** [comment]
I have similar error for !Join:

unacceptable node kind for !<!Join> tag; it should be "scalar", not "sequence"

**Comment by farmerbean** [comment]
I had this issue too.  Custom tags setup in user.settings, etc.

Removed cloudformation plugin
Removed rhel yaml plugin

Added in cloudformation plugin
(cloudformation plugin installed rhel yaml dependency)

Problem now (temporarily I assume!) resolved.

**Comment by deepu105** [comment]
This works for me, but if you are using scalar types with those you will have issues
```
    "yaml.customTags": [
        "!fn",
        "!And",
        "!If",
        "!Not",
        "!Equals",
        "!Or",
        "!FindInMap sequence",
        "!Base64",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select",
        "!Split",
        "!Join sequence"
    ]
```

**Comment by sgtoj** [comment]
I resolved a similar issue by renaming my template to end with `yaml` extension. Same file throws errors with `yml` extension.

**Comment by mixmatch** [comment]
Is there a fix in the works for this? Have to disable validation make the editor usable:
`"yaml.validate": false`

**Comment by JPinkney** [comment]
Not currently. Would you like to contribute one? I can show you where to get started.

**Comment by mixmatch** [comment]
I'm not familiar with vscode extensions but I can take a look...

**Comment by JPinkney** [comment]
I believe the problem stems from: https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/yamlParser.ts#L256 where we use the custom tags and put them into [the yaml-ast-parser](https://github.com/mulesoft-labs/yaml-ast-parser/issues).

**Comment by tanduong** [comment]
It appears that after added "!If sequence" to the list of custom tags, I need to restart my editor and it will work.

**Comment by mandersondesign** [comment]
I ended up using this one so far...

```
"yaml.customTags": [
        "!fn",
        "!And",
        "!If",
        "!Not",
        "!Equals",
        "!Or",
        "!FindInMap sequence",
        "!Base64",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select",
        "!Split",
        "!Join sequence",
        "!Select sequence"
    ]
```

**Comment by strannik19** [comment]
none of the customTags options work when you mix and max sequence and scalar. it only uses the first one and doesn't allow for the alternative option. so far the only way to go is `"yaml.validate": false`.

**Comment by zoellner** [comment]
Replacing `"!Equals",` with `"!Equals sequence",` in the settings worked for me for this

**Comment by JPinkney** [comment]
Hi everyone! Its been a long time coming but I've finally got custom tags working when you have a tag with multiple different types. That means in the next version you're able to do:

```
"yaml.customTags": [
        "!myTag1 scalar",
        "!myTag1 mapping",
        "!myTag1 sequence",
    ]
```
and the document will report no errors if you have something like:

```
test: !myTag1 hello_world

test2: !myTag1
  hello: world

test3: !myTag1
  - hello: world
```

**Comment by Splike** [comment]
@JPinkney That's pretty cool! If I just have
```yaml
"yaml.customTags": [
        "!myTag1"
    ]
```

I think it would make sense that scalar, mapping and sequence should all be accepted for `!myTag1`

**Comment by lorcanoeire** [comment]
This is the full set of required configurations (worked for me):

`{
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Material Theme Darker",
    // Custom tags for the parser to use
    "yaml.customTags": [
        "!And scalar",
        "!And mapping",
        "!And sequence",                
        "!If scalar",
        "!If mapping",
        "!If sequence",                
        "!Not scalar",
        "!Not mapping",
        "!Not sequence",                
        "!Equals scalar",
        "!Equals mapping",
        "!Equals sequence",                
        "!Or scalar",
        "!Or mapping",
        "!Or sequence",                
        "!FindInMap scalar",
        "!FindInMap mappping",        
        "!FindInMap sequence",
        "!Base64 scalar",
        "!Base64 mapping",
        "!Base64 sequence",                
        "!Cidr scalar",
        "!Cidr mapping",
        "!Cidr sequence",                
        "!Ref scalar",
        "!Ref mapping",
        "!Ref sequence",                
        "!Sub scalar",
        "!Sub mapping",
        "!Sub sequence",                
        "!GetAtt scalar",
        "!GetAtt mapping",
        "!GetAtt sequence",                
        "!GetAZs scalar",
        "!GetAZs mapping",
        "!GetAZs sequence",                
        "!ImportValue scalar",
        "!ImportValue mapping",
        "!ImportValue sequence",                
        "!Select scalar",
        "!Select mapping",
        "!Select sequence",
        "!Split scalar",
        "!Split mapping",
        "!Split sequence",                
        "!Join scalar",
        "!Join mapping",
        "!Join sequence"                
    ],
    // Enable/disable default YAML formatter (requires restart)
    "yaml.format.enable": true,
}`

**Comment by benkehoe** [comment]
The CloudFormation extension has added support to do this configuration automatically. https://github.com/awslabs/aws-cfn-lint-visual-studio-code/pull/65
