### ISSUE TITLE
Support textDocument/foldingRange feature

### ISSUE THREAD

**Issue by davidshen84** [redhat-developer/yaml-language-server#776]
### Is your enhancement related to a problem? Please describe.

When editing large yaml files, it is hard to track which node you are editing.

### Describe the solution you would like

Provide folding capabilities to LSP.

### Describe alternatives you have considered

`lsp-origami-mode` works to some extent out of the box. But the folding behaviour gets unpredictable when the current node is below the 2nd level.

**Comment by gorkem** [comment]
yaml-language-server does support the `textDocument/foldingRange`. Can you provide a more specific description of the issue that you see?  I suspect that the client(editor) is not enabling the `textDocument/foldingRange` for YAML LSP for some reason. Are you using vscode?

**Comment by davidshen84** [comment]
Hi Gorkem,

I am using LSP in Emacs. https://emacs-lsp.github.io/lsp-mode/

LSP in Emacs does not support folding directly. The folding function is
provided by other packages like `hs-minor-mode` or `origami-mode`. I guess
the integration between Emacs and the folding packages is not working.

Thanks.
