### ISSUE TITLE
Configuration to enable/disable schema store

### ISSUE THREAD

**Issue by stephenmichaelf** [redhat-developer/yaml-language-server#78]
@JPinkney @gorkem 

If you happen to be working in a workspace that has a folder/file path that matches one of the schema store json files, it supersedes what is set by the user. I am guessing this is because it comes later in the array.

Can we add a configuration option to not call:

[setSchemaStoreSettingsIfNotSet()](https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L221)

I would prefer to not make the HTTP request in the first place.

**Comment by JPinkney** [comment]
This has been added in 0.3.0. We now have a setting called yaml.schemaStore.enable that when set to false, stops the extension from automatically pulling schemas from the schema store.
