### ISSUE TITLE
bad completion with array of objects

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/yaml-language-server#793]
## Describe the bug
Given that I have an array of objects in my schema; if in my YAML file, I add an array item, return to the line and invoke completion, the completion wrongly provides "{} - (array item) object" instead of the different properties available in my current object.

Here's a visual example:
![test2](https://user-images.githubusercontent.com/3750300/196362726-4524c793-14b4-4de1-a0d4-9613f7e8a603.gif)

My JSON schema is the following:
``` json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "prop1": {
        "type": "string"
      },
      "prop2": {
        "type": "string"
      },
      "prop3": {
        "type": "string"
      }
    }
  }
}
```

## Expected Behavior
In my example, completion should provide "prop2" and "prop3", and not "{} - (array item) object"

## Current Behavior
In my example, completion actually provide "{} - (array item) object", and not "prop2" and "prop3"

## Steps to Reproduce
1. given the following YAML file:
``` yaml
- prop1: a
  
```
2. go to 2nd line, write 2 spaces, and then do "Ctrl+Tab"
3. you get the wrong completion list, that is to say "{} - (array item) object", and not "prop2" and "prop3"

## Environment
- Windows
- Visual Studio Code
- YAML extension v1.10.1 and also YAML extension v1.11.10112022

**Comment by chuyangguangshin** [comment]
I reproduce this issue in version 1.10.1 . And find that it suggest properties correctly with version 0.23.0 .

**Comment by gorkem** [comment]
@msivasubramaniaan can you take a look at this one? Feels like we fixed this before.
