### ISSUE TITLE
document how to use it with other editors

### ISSUE THREAD

**Issue by ibotty** [redhat-developer/yaml-language-server#8]
I'd like to use it with neovim's language-server client. How do I start it? For e.g. rust, I'll just have to provide the path to start it. How do I integrate yaml-language-server?

**Comment by JPinkney** [comment]
Hi, I'm not exactly sure how neovim does this language server stuff but heres how its done for [atom](https://github.com/liuderchi/ide-yaml/blob/master/src/main.js#L21) and [vscode](https://github.com/redhat-developer/vscode-yaml/blob/master/src/extension.ts#L25). The process should be similar. In both those cases we are just using the [node module we provide](https://www.npmjs.com/package/yaml-language-server). If you need anymore help let me know! (I'm not familiar with neovim's language server/plugin situation but I can try to help!)

**Comment by ibotty** [comment]
Yes, I think I figured it out. Should I submit a pull request to add
documentation to the readme?

**Comment by JPinkney** [comment]
It depends, if you want to add how to set it up generally then yes but if you're specifically wanting to add something for neovim i'm not sure, it depends. (I'm still not sure how neovim plugins work) but ideally we would have one plugin for each code editor that wants to consume it so the neovim code could live in a plugin. If plugins aren't possible/its very cumbersome to install we can include it in the readme! (Also if plugins are possible and you created one you could put that in the readme under the clients section)

**Comment by ibotty** [comment]
I needed the information, how you start the server (`--stdio`). BTW: why don't you install a binary link in node's bin directory?

**Comment by JPinkney** [comment]
I've added documentation so that users know they can start the server with --stdio

**Comment by gorkem** [comment]
Is there anything else left to do here? Should we close?

**Comment by JPinkney** [comment]
I think we can close
