### ISSUE TITLE
Embedding yaml language server in other language servers

### ISSUE THREAD

**Issue by priyamsahoo** [redhat-developer/yaml-language-server#803]
## Summary
Hey,
I wanted to know if there's some documentation I can refer to for using yaml-language-server with other ls. Help would be much appreciated if someone could tell me how I should invoke yaml-ls for auto-completions in some other ls.

**Comment by gorkem** [comment]
This depends on the client rather than the server. Here is the embedded languages document for vscode that may be helpful. https://code.visualstudio.com/api/language-extensions/embedded-languages
