### ISSUE TITLE
Need confirmation of my understanding of the schema file type.

### ISSUE THREAD

**Issue by userunk325** [redhat-developer/yaml-language-server#835]
From reading up I understand that the schema file used for validation **has**  to be a json schema file. Is this a correct understanding?
 Is there any way to instead use a yaml schema file ?

Thanks.

**Comment by gorkem** [comment]
Yes, since version 0.11.1 you can use YAML schema files. On the schema settings [section](https://github.com/redhat-developer/yaml-language-server#using-yamlschemas-settings) of the README there is a reference to YAML schemas.
