### ISSUE TITLE
Add github discussion forms json schema

### ISSUE THREAD

**Issue by Wladefant** [redhat-developer/yaml-language-server#842]
### Is your enhancement related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I am always frustrated when [...]

### Describe the solution you would like
Please add a github discussion forms json schema as was done with the github issue form 

### Additional context
Here is the [syntax for the discussion forms](https://docs.github.com/en/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms)

**Comment by gorkem** [comment]
The yaml-language-server does not ship any schemas. It does have integration with [schemastore](https://www.schemastore.org/json/) and can use it if it is made available in there.

**Comment by Wladefant** [comment]
Understood
