### ISSUE TITLE
How to disable wrong order rule?

### ISSUE THREAD

**Issue by A-Siam** [redhat-developer/yaml-language-server#872]
## Summary
I want to disable the "wrong order" error how to set this up, or is this even related to the language server itself? 
## Relevant information

- yaml-language-server version: 1.12
- node_version: 18.15.0
- client: nvim_lspconfig
- os: ubuntu 22.04

**Comment by gorkem** [comment]
Setting the `yaml.keyOrdering` setting to false should disable it. False is the default value but I am not a regular nvim user to be able to tell if this is the case there.

**Comment by shidoro** [comment]
I have the same issue. I tried explicitly setting `yaml.keyOrdering = false` but it doesn't work. I also rolled back to v1.11.0

**Comment by memchr** [comment]
> but where do you specify that yaml.keyOrdering
For `lspconfig', it's in the `settings' key of each server's setup() parameter.
e.g.
```lua
lspconfig.yamlls.setup {
	settings = {
		yaml = {
			keyOrdering = false,
		}
	}
}
```

**Comment by A-Siam** [comment]
thanks, everyone worked for me

**Comment by bharrispepsico** [comment]
it does seem to be a bug in 1.12.0, I also have downgraded to 1.11.0 and it seems to work correctly now.
