### ISSUE TITLE
Should we set a schema expire time?

### ISSUE THREAD

**Issue by 928PJY** [redhat-developer/yaml-language-server#89]
For now, if the schema is an external resource, we can not apply the latest schema once they changed, because the VSCode will cache those files to provide a better performance. but if we want to force cleaning up the cache by reopening VS Code, it doesn't work, I have created an [issue](https://github.com/Microsoft/vscode/issues/58362) to track.

On the other hand, should we set a expire time for those external schema files? maybe 10 minutes?
I have tried to set the  [`cache-control` header](https://github.com/928PJY/yaml-language-server/blob/object/src/server.ts#L160), but it doesn't work.
@JPinkney

**Comment by 928PJY** [comment]
yeah, the schema service is storing the schema in memory,
but if there is a custom contribution which returns an external schema URL, when I debug it, it can always hit this [line](https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L161), I think that means there must be a http request, but if it always get the same response even the resouce changed, and the same after I reopen the vscode.

**Comment by JPinkney** [comment]
In that case I don't think the caching would be done in this extension. I'm not entirely sure where that caching would be done tbh but I'll try looking around. If I'm understanding correctly first http request is made and it gets results, then the schema is changed at some external location, then the next http request to that same location gets the old results not the new ones.

**Comment by 928PJY** [comment]
maybe I should create a simple sample to reproduce this issues which can get rid of our logic

**Comment by JPinkney** [comment]
@928PJY Is this still an issue or can I close this?

**Comment by 928PJY** [comment]
of course, you can close it, it is caused by the raw content update latency of Github.
Thanks for your help.
