### ISSUE TITLE
Can we extract the schema utility logic to anothor npm package?

### ISSUE THREAD

**Issue by 928PJY** [redhat-developer/yaml-language-server#90]
those logics can also be used for other purposes besides the language server @JPinkney

**Comment by JPinkney** [comment]
What specifically were you thinking that needs to be abstracted?

**Comment by 928PJY** [comment]
sorry for the late response, the logic to parse the YAML schema can be used for other cases.
anyway, it is nice to have.

**Comment by gorkem** [comment]
This is not really in the scope of this project and additional work for the core contributors of the project. Closing as won't fix.
