### ISSUE TITLE
documentation -- schema relative path isn't clear

### ISSUE THREAD

**Issue by mlibbey** [redhat-developer/yaml-language-server#97]
The readme says
``Your schema must be a relative path and not an absolute path``
Relative to what? The yaml file being edited? The settings.json file? (I have a project where my yaml is in one git repo, and the schema is in another git repo -- so, need to traverse folder paths  -- would be nice to have an example to follow!

**Comment by JPinkney** [comment]
Its relative to the root of the project so if you had something like:

myProject
&nbsp;&nbsp;&nbsp;&nbsp;> myYamlFile.yaml

you can do 

```
yaml.schemas: {
    "http://json.schemastore.org/composer": "/myYamlFile.yaml"
}
```

and it will associate the composer schema with myYamlFile.yaml. I've added this in the README. Let me know if you find anything else that is confusing in the README so that I can fix it up!

**Comment by tterranigma** [comment]
It is still not clear to me. The README says:

>> [...] the schema (**placed on the left**) is applied to the glob pattern on the right. Your schema can be local or online. Your **schema path** must be relative to the project root and not an absolute path to the schema.

Is this a mistake? Should it be that the glob pattern should be relative?

Also, how to define a schema via a local path? There is no example.

**Comment by JPinkney** [comment]
If I have project structure:
My-Top-Level-Folder
&nbsp;&nbsp;testing
&nbsp;&nbsp;&nbsp;&nbsp;composer.json

and in the settings I do:
"yaml.schemas": {
        "./testing/composer.json": "/*"
}

Composer.json schema will be applied to every yaml file underneath My-Top-Level-Folder.

**Comment by tterranigma** [comment]
Thanks for the clarification. So, if I want to use a global schema file, I cannot do that right?

I saw someone specify the schema file with:

```
"file:///home/me/.../schema.json": "/*"
```

That is wrong then, right?

**Comment by JPinkney** [comment]
For some reason I thought that wouldn't work but indeed it does! So it looks like its time for me to change the docs a bit 😄. 

I was able to get it working by doing:
```
"yaml.schemas": {
        "file:///Users/joshpinkney/Documents/custom-tags/yaml-language-server/testing/composer.json": "/test2.yaml"
    }
```

**Comment by tterranigma** [comment]
Thanks for the support!

**Comment by JPinkney** [comment]
No worries! I'm glad to help!

**Comment by AckslD** [comment]
@nkakouros Sorry to write in a closed issue but was just wondering if this worked for you? When I specify a global schema it seems it's applied to all files even if they don't match glob. If it's a relative to file or root then this does not happen. Have you perhaps seen something similar?
